"""Physics engine for galaxy collision simulation governed by wave refraction theory.

Gravity is not a fundamental force. It is not “curvature of the fabric of space-time”.
It is classical wave refraction.

In the Unified Field Theory, all matter consists of localized concentrations of
electromagnetic wave energy (matter knots). Galaxies are extended clouds of
energy density in the universal electromagnetic field that establish an inhomogeneous
refractive index gradient:

    n(r) = 1 + (2 / c^2) * Phi(r)

where Phi(r) is the potential generated by the total energy density distribution.
The speed of electromagnetic influences is v(r) = c / n(r).
Each circulating matter knot (star) is steered by the differential wave speed
across its finite diameter:

    a = - (c^2 / (2 * n)) * grad(n) ~= - grad(Phi)
"""

from __future__ import annotations

import math
import random
from collections import deque
from dataclasses import dataclass, field
from typing import Deque, List, Tuple

try:
    from .physics_fast import fast_step_stars  # type: ignore
    FAST_PHYSICS_AVAILABLE = True
except ImportError:
    try:
        from physics_fast import fast_step_stars  # type: ignore
        FAST_PHYSICS_AVAILABLE = True
    except ImportError:
        fast_step_stars = None
        FAST_PHYSICS_AVAILABLE = False


@dataclass
class GalaxyConfig:
    """Configuration parameters for an energy density cloud galaxy."""

    mass: float = 1.0  # Relative mass (1.0 = ~10^11 solar masses scaled)
    disk_radius: float = 90.0  # Visual/exponential scale radius (pixels)
    softening: float = 32.0  # M-res smoothing length (aperture scale)
    num_stars: int = 700  # Number of representative matter knots
    inclination_deg: float = 20.0  # Disk tilt angle in degrees
    spiral_arms: int = 2  # Number of spiral arms
    spiral_pitch: float = 0.28  # Spiral pitch factor
    color_rgb: Tuple[int, int, int] = (120, 200, 255)  # Particle tint


@dataclass
class StarKnot:
    """A localized circulating wave packet (star) within the galaxy's energy cloud."""

    x: float
    y: float
    vx: float
    vy: float
    galaxy_id: int
    r_initial: float
    base_color: Tuple[int, int, int]

    def update_position(self, dt: float, ax: float, ay: float) -> None:
        """First step of Verlet / Leapfrog position integration."""
        self.x += self.vx * dt + 0.5 * ax * dt * dt
        self.y += self.vy * dt + 0.5 * ay * dt * dt

    def update_velocity(self, dt: float, ax_old: float, ay_old: float, ax_new: float, ay_new: float) -> None:
        """Second step of Verlet / Leapfrog velocity integration."""
        self.vx += 0.5 * (ax_old + ax_new) * dt
        self.vy += 0.5 * (ay_old + ay_new) * dt


@dataclass
class GalaxyCenter:
    """The central dense core / nucleus of a galaxy."""

    x: float
    y: float
    vx: float
    vy: float
    mass: float
    softening: float
    disk_radius: float
    galaxy_id: int

    def update_position(self, dt: float, ax: float, ay: float) -> None:
        self.x += self.vx * dt + 0.5 * ax * dt * dt
        self.y += self.vy * dt + 0.5 * ay * dt * dt

    def update_velocity(self, dt: float, ax_old: float, ay_old: float, ax_new: float, ay_new: float) -> None:
        self.vx += 0.5 * (ax_old + ax_new) * dt
        self.vy += 0.5 * (ay_old + ay_new) * dt


class GalaxyCollisionSimulation:
    """Simulates two spiral galaxies interacting through their refractive energy clouds."""

    # Gravitational coupling constant in simulation units
    G: float = 18000.0

    def __init__(
        self,
        center_x: float = 550.0,
        center_y: float = 425.0,
        m1: float = 1.0,
        m2: float = 0.7,
        separation: float = 520.0,
        impact_param: float = 120.0,
        rel_velocity: float = 46.0,
        tilt1_deg: float = 15.0,
        tilt2_deg: float = -45.0,
        softening: float = 34.0,
        num_stars_per_galaxy: int = 700,
        dynamical_friction: float = 0.45,
    ) -> None:
        self.cx = center_x
        self.cy = center_y

        # Parameters
        self.m1 = m1
        self.m2 = m2
        self.separation = separation
        self.impact_param = impact_param
        self.rel_velocity = rel_velocity
        self.tilt1_deg = tilt1_deg
        self.tilt2_deg = tilt2_deg
        self.softening = softening
        self.num_stars = num_stars_per_galaxy
        self.friction_coeff = dynamical_friction

        self.time_elapsed: float = 0.0
        self.paused: bool = False
        self.speed_multiplier: float = 1.0

        # Galaxy cores and star populations
        self.g1: GalaxyCenter = None  # type: ignore
        self.g2: GalaxyCenter = None  # type: ignore
        self.stars: List[StarKnot] = []

        self.reset()

    def reset(self) -> None:
        """Reset the galaxies to their initial positions and velocities."""
        self.time_elapsed = 0.0

        # Initial geometry:
        # Center of mass at (self.cx, self.cy)
        total_m = self.m1 + self.m2
        frac1 = self.m2 / total_m
        frac2 = self.m1 / total_m

        # Position galaxy 1 on the left, galaxy 2 on the right
        # with vertical offset set by impact_param
        x1 = self.cx - self.separation * frac1
        y1 = self.cy - self.impact_param * frac1

        x2 = self.cx + self.separation * frac2
        y2 = self.cy + self.impact_param * frac2

        # Relative velocity directed primarily horizontally, with impact vector
        vx1 = (self.rel_velocity * 0.5) * (self.m2 / total_m)
        vy1 = (self.impact_param / max(self.separation, 1.0)) * vx1 * 0.5

        vx2 = -(self.rel_velocity * 0.5) * (self.m1 / total_m)
        vy2 = -(self.impact_param / max(self.separation, 1.0)) * vx2 * 0.5

        self.g1 = GalaxyCenter(
            x=x1,
            y=y1,
            vx=vx1,
            vy=vy1,
            mass=self.m1,
            softening=self.softening,
            disk_radius=95.0 * math.sqrt(self.m1),
            galaxy_id=1,
        )

        self.g2 = GalaxyCenter(
            x=x2,
            y=y2,
            vx=vx2,
            vy=vy2,
            mass=self.m2,
            softening=self.softening * 0.9,
            disk_radius=85.0 * math.sqrt(self.m2),
            galaxy_id=2,
        )

        # Generate stars for both galaxies
        self.stars.clear()
        self._populate_galaxy_stars(
            self.g1,
            num_stars=self.num_stars,
            tilt_deg=self.tilt1_deg,
            color_rgb=(130, 210, 255),
        )
        self._populate_galaxy_stars(
            self.g2,
            num_stars=int(self.num_stars * (self.m2 / max(self.m1, 0.2))),
            tilt_deg=self.tilt2_deg,
            color_rgb=(255, 195, 120),
        )

    def _populate_galaxy_stars(
        self,
        core: GalaxyCenter,
        num_stars: int,
        tilt_deg: float,
        color_rgb: Tuple[int, int, int],
    ) -> None:
        """Create a rotating exponential disk of matter knots with spiral arm structure."""
        random.seed(core.galaxy_id * 104729 + 42)
        tilt_rad = math.radians(tilt_deg)
        cos_t = math.cos(tilt_rad)
        sin_t = math.sin(tilt_rad)

        r_max = core.disk_radius * 2.2
        r_core = core.softening * 0.5

        for i in range(num_stars):
            # Exponential radial distribution
            u = random.random()
            r = r_core + (-math.log(1.0 - 0.98 * u)) * (core.disk_radius * 0.55)
            r = min(r, r_max)

            # Spiral arm phase angle
            arm = random.choice([0, 1])
            phi_base = (2.0 * math.pi * arm) / 2.0
            phi_spiral = phi_base + 0.35 * math.log(r / r_core)
            # Add angular dispersion to give natural disk thickness
            phi = phi_spiral + random.gauss(0.0, 0.28)

            # Circular rotation velocity derived from refractive potential gradient
            # Phi = G * M / sqrt(r^2 + eps^2)
            # v_circ = sqrt(r * |dPhi/dr|) = sqrt(G * M * r^2 / (r^2 + eps^2)^(3/2))
            eff_dist_sq = r * r + core.softening * core.softening
            v_circ = math.sqrt((self.G * core.mass * r * r) / (eff_dist_sq * math.sqrt(eff_dist_sq)))

            # Position in disk plane
            px_disk = r * math.cos(phi)
            py_disk = r * math.sin(phi)

            # Velocity in disk plane (tangential to radius vector)
            vx_disk = -v_circ * math.sin(phi)
            vy_disk = v_circ * math.cos(phi)

            # Rotate by galaxy inclination/tilt
            px = px_disk * cos_t - py_disk * sin_t
            py = px_disk * sin_t + py_disk * cos_t

            vx = vx_disk * cos_t - vy_disk * sin_t
            vy = vx_disk * sin_t + vy_disk * cos_t

            star = StarKnot(
                x=core.x + px,
                y=core.y + py,
                vx=core.vx + vx,
                vy=core.vy + vy,
                galaxy_id=core.galaxy_id,
                r_initial=r,
                base_color=color_rgb,
            )
            self.stars.append(star)

    def _accel_from_core(
        self, px: float, py: float, core: GalaxyCenter
    ) -> Tuple[float, float]:
        """Compute gravitational acceleration on a point from a galaxy's energy cloud."""
        dx = px - core.x
        dy = py - core.y
        dist_sq = dx * dx + dy * dy + core.softening * core.softening
        dist = math.sqrt(dist_sq)
        # a = - G * M * r / (r^2 + eps^2)^(3/2)
        inv_cube = 1.0 / (dist_sq * dist)
        mag = self.G * core.mass * inv_cube
        return -mag * dx, -mag * dy

    def step(self, dt: float) -> None:
        """Advance the simulation by dt seconds using Symplectic Verlet integration."""
        if self.paused:
            return

        dt = min(dt * self.speed_multiplier, 0.04)
        self.time_elapsed += dt

        # 1. Accelerations between the two galaxy centers
        dx12 = self.g2.x - self.g1.x
        dy12 = self.g2.y - self.g1.y
        r12_sq = dx12 * dx12 + dy12 * dy12
        softened_r12_sq = r12_sq + (self.g1.softening + self.g2.softening) ** 2
        softened_r12 = math.sqrt(softened_r12_sq)

        # Gravitational attraction between cores
        f_grav_mag = self.G / (softened_r12_sq * softened_r12)
        ax1_grav = f_grav_mag * self.g2.mass * dx12
        ay1_grav = f_grav_mag * self.g2.mass * dy12

        ax2_grav = -f_grav_mag * self.g1.mass * dx12
        ay2_grav = -f_grav_mag * self.g1.mass * dy12

        # Dynamical friction from overlapping energy clouds
        # F_drag = - gamma * (M1 * M2) / (r^2 + sigma^2) * (V_rel / (V_rel^2 + v_disp^2)^(1/2))
        dvx = self.g2.vx - self.g1.vx
        dvy = self.g2.vy - self.g1.vy
        v_rel_sq = dvx * dvx + dvy * dvy
        v_rel = math.sqrt(v_rel_sq) + 1e-4

        f_drag_factor = (
            self.friction_coeff
            * 320.0
            * (self.g1.mass * self.g2.mass)
            / (softened_r12_sq * math.sqrt(v_rel_sq + 400.0))
        )

        ax1_drag = f_drag_factor * dvx / self.g1.mass
        ay1_drag = f_drag_factor * dvy / self.g1.mass

        ax2_drag = -f_drag_factor * dvx / self.g2.mass
        ay2_drag = -f_drag_factor * dvy / self.g2.mass

        ax1_old = ax1_grav + ax1_drag
        ay1_old = ay1_grav + ay1_drag
        ax2_old = ax2_grav + ax2_drag
        ay2_old = ay2_grav + ay2_drag

        # Advance galaxy positions
        self.g1.update_position(dt, ax1_old, ay1_old)
        self.g2.update_position(dt, ax2_old, ay2_old)

        # 2. Advance all stars' positions
        star_accels_old: List[Tuple[float, float]] = []
        for star in self.stars:
            ax1, ay1 = self._accel_from_core(star.x, star.y, self.g1)
            ax2, ay2 = self._accel_from_core(star.x, star.y, self.g2)
            tot_ax = ax1 + ax2
            tot_ay = ay1 + ay2
            star_accels_old.append((tot_ax, tot_ay))
            star.update_position(dt, tot_ax, tot_ay)

        # 3. Compute new accelerations for galaxy cores at updated positions
        dx12_new = self.g2.x - self.g1.x
        dy12_new = self.g2.y - self.g1.y
        r12_sq_new = dx12_new * dx12_new + dy12_new * dy12_new
        softened_r12_sq_new = r12_sq_new + (self.g1.softening + self.g2.softening) ** 2
        softened_r12_new = math.sqrt(softened_r12_sq_new)

        f_grav_mag_new = self.G / (softened_r12_sq_new * softened_r12_new)
        ax1_grav_new = f_grav_mag_new * self.g2.mass * dx12_new
        ay1_grav_new = f_grav_mag_new * self.g2.mass * dy12_new
        ax2_grav_new = -f_grav_mag_new * self.g1.mass * dx12_new
        ay2_grav_new = -f_grav_mag_new * self.g1.mass * dy12_new

        dvx_new = self.g2.vx - self.g1.vx
        dvy_new = self.g2.vy - self.g1.vy
        v_rel_sq_new = dvx_new * dvx_new + dvy_new * dvy_new

        f_drag_factor_new = (
            self.friction_coeff
            * 320.0
            * (self.g1.mass * self.g2.mass)
            / (softened_r12_sq_new * math.sqrt(v_rel_sq_new + 400.0))
        )
        ax1_drag_new = f_drag_factor_new * dvx_new / self.g1.mass
        ay1_drag_new = f_drag_factor_new * dvy_new / self.g1.mass
        ax2_drag_new = -f_drag_factor_new * dvx_new / self.g2.mass
        ay2_drag_new = -f_drag_factor_new * dvy_new / self.g2.mass

        ax1_new = ax1_grav_new + ax1_drag_new
        ay1_new = ay1_grav_new + ay1_drag_new
        ax2_new = ax2_grav_new + ax2_drag_new
        ay2_new = ay2_grav_new + ay2_drag_new

        # Update galaxy velocities
        self.g1.update_velocity(dt, ax1_old, ay1_old, ax1_new, ay1_new)
        self.g2.update_velocity(dt, ax2_old, ay2_old, ax2_new, ay2_new)

        # 4. Compute new accelerations for all stars and update their velocities
        for i, star in enumerate(self.stars):
            ax1, ay1 = self._accel_from_core(star.x, star.y, self.g1)
            ax2, ay2 = self._accel_from_core(star.x, star.y, self.g2)
            tot_ax_new = ax1 + ax2
            tot_ay_new = ay1 + ay2
            ax_old, ay_old = star_accels_old[i]
            star.update_velocity(dt, ax_old, ay_old, tot_ax_new, tot_ay_new)

    def get_refractive_potential(self, px: float, py: float) -> float:
        """Compute total wave-refractive potential Phi at point (px, py)."""
        d1_sq = (px - self.g1.x) ** 2 + (py - self.g1.y) ** 2 + self.g1.softening ** 2
        d2_sq = (px - self.g2.x) ** 2 + (py - self.g2.y) ** 2 + self.g2.softening ** 2
        phi1 = (self.G * self.g1.mass) / math.sqrt(d1_sq)
        phi2 = (self.G * self.g2.mass) / math.sqrt(d2_sq)
        return phi1 + phi2

    def distance_between_cores(self) -> float:
        return math.hypot(self.g2.x - self.g1.x, self.g2.y - self.g1.y)

    def relative_velocity(self) -> float:
        return math.hypot(self.g2.vx - self.g1.vx, self.g2.vy - self.g1.vy)
