import fs from 'fs';
import path from 'path';

// Read textbookData.ts
const filePath = path.join(process.cwd(), 'src/data/textbookData.ts');
let content = fs.readFileSync(filePath, 'utf8');

// Find where PHYSICS_CHEMISTRY_TEXTBOOK ends
const endPhysicsIdx = content.indexOf('  "filename": "Iris_Number_System-04-Volume_IV_Physics_etc.adoc"\n};');

if (endPhysicsIdx === -1) {
  console.error("Could not find end of PHYSICS_CHEMISTRY_TEXTBOOK");
  process.exit(1);
}

const beforePart = content.slice(0, endPhysicsIdx + '  "filename": "Iris_Number_System-04-Volume_IV_Physics_etc.adoc"\n};'.length);

const sec1Content = [
  "=== The Fallacy of the Continuum Complex Plane and Real Bivector Kinematics",
  "",
  "In 19th and 20th-century mathematical analysis and electrical engineering, linear signal processing was built upon the algebraic convention of the “complex plane” \\( \\mathbb { C } \\) and the imaginary unit \\( i = \\sqrt { - 1 } \\). While computationally effective as an algorithmic shorthand for handling two-dimensional rotations and phase shifts, the conventional interpretation of \\( \\mathbb { C } \\) introduced major epistemological and ontological fallacies:",
  "",
  "1. **The Continuum Fallacy of Imaginary Quantities**:",
  "   Conventional analysis treats \\( i \\) as an abstract, non-physical scalar existing outside the real number line, operating over an uncountably infinite continuum of complex values. In the actual conduct of science and engineering, there are no imaginary quantities or continuum infinities; physical observations consist of measurements over discrete spatial-temporal resolution grids \\( \\mathcal { G } _ N \\). Examples include voltages, currents, temperatures, pressures, lengths, angles, etc.",
  "",
  "2. **Geometric Interpretation: Unit Oriented Bivectors**:",
  "   In real Geometric Algebra, the algebraic entity satisfying \\( \\mathbf { I } ^ 2 = - 1 \\) is not an imaginary scalar, but a real, oriented **unit bivector** \\( \\mathbf { I } \\) representing an oriented 2D plane segment. In a two-dimensional real space \\( \\mathbb { R } ^ 2 \\) spanned by orthogonal unit vectors \\( e _ 1, e _ 2 \\) (with \\( e _ 1 ^ 2 = 1 \\), \\( e _ 2 ^ 2 = 1 \\)), the unit bivector is defined by the geometric product:",
  "   \\[ \\mathbf { I } = e _ 1 e _ 2 = e _ 1 \\wedge e _ 2 \\]",
  "   By the fundamental anti-commutativity of orthogonal vectors (\\( e _ 1 e _ 2 = - e _ 2 e _ 1 \\)), computing the square of \\( \\mathbf { I } \\) yields a purely real result:",
  "   \\[ \\mathbf { I } ^ 2 = ( e _ 1 e _ 2 ) ( e _ 1 e _ 2 ) = - e _ 1 ( e _ 1 e _ 2 ) e _ 2 = - ( e _ 1 e _ 1 ) ( e _ 2 e _ 2 ) = - 1 \\]",
  "   Multiplying a real vector \\( \\mathbf { v } = v _ 1 e _ 1 + v _ 2 e _ 2 \\) by \\( \\mathbf { I } \\) rotates \\( \\mathbf { v } \\) by \\( 90 ^ \\circ \\) in the \\( e _ 1 \\wedge e _ 2 \\) plane. Thus, Euler’s relation \\( e ^ { \\mathbf { I } \\theta } = \\cos \\theta + \\mathbf { I } \\sin \\theta \\) is an exact real geometric rotor that precesses real vectors in a real two-dimensional subspace, removing the need for imaginary numbers or complex planes.",
  "",
  "3. **Sufficiency of Lightweight Geometric Algebras**:",
  "   While field dynamics on discrete multiscale resolution grids is fully described by the 64-dimensional Clifford Algebra \\( Cl ( 4 , 1 , 1 ) \\) under the Master Field Equation \\( D F = J \\), planar signal analysis requires far lighter geometric structures. For example:",
  "   * **The One-Dimensional Clifford Algebra \\( Cl ( 0 , 1 ) \\)**: Spanned by a single generator \\( e _ 1 \\) with \\( e _ 1 ^ 2 = - 1 \\). Elements are real linear combinations \\( a + b e _ 1 \\). This algebra is naturally isomorphic to \\( \\mathbb { C } \\) as a vector space, but every term remains a purely real multivector.",
  "   * **The Two-Dimensional Clifford Algebra \\( Cl ( 2 , 0 ) \\)**: Spanned by real orthogonal vectors \\( e _ 1, e _ 2 \\) with \\( e _ 1 ^ 2 = 1, e _ 2 ^ 2 = 1 \\). The even subalgebra \\( Cl ^ + ( 2 , 0 ) \\) consists of elements \\( a + b e _ { 1 2 } \\), providing a complete, coordinate-free real geometric phase plane.",
  "   * **The Three-Dimensional Euclidean Geometric Algebra \\( Cl ( 3 , 0 ) \\)** (often designated as the Spatial Vector Algebra): Spanned by three spatial basis vectors \\( e _ 1, e _ 2, e _ 3 \\), avoiding relativistic continuum assumptions and frames of reference. In this algebra, the pseudoscalar \\( \\mathbf { I } = e _ 1 e _ 2 e _ 3 \\) satisfies \\( \\mathbf { I } ^ 2 = - 1 \\) and commutes with all grade elements, serving as an intrinsic 3D phase-rotation operator.",
  "",
  "4. **Matrix Operator Representation without Geometric Algebra**:",
  "   Even without Geometric Algebra, any digital signal vector \\( \\mathbf { x } = [ x [ 0 ] , x [ 1 ] , \\dots , x [ N - 1 ] ] ^ T \\in \\mathbb { R } ^ N \\) on a finite resolution grid \\( \\mathcal { G } _ N \\) can be processed using purely real orthogonal matrix operators. The bivector rotation operator \\( \\mathbf { I } \\) maps directly to the real anti-symmetric block generator matrix:",
  "   \\[ J = \\begin {pmatrix} 0 & - 1 \\\\ 1 & 0 \\end {pmatrix} \\]",
  "   satisfying \\( J ^ 2 = - I _ 2 \\). Consequently, all classical transforms can be executed as real matrix-vector operations on real physical analog or digital signal channels."
].join("\n");

const sec2Content = [
  "=== Unified Operator Kernel Formulation for Conventional Transforms",
  "",
  "Let \\( \\mathcal { G } _ N = \\{ n \\delta \\mid n \\in \\{ 0 , 1 , \\dots , N - 1 \\} \\} \\) be a discrete multiscale spatial-temporal grid with uniform step spacing \\( \\delta \\). Every major conventional linear transform—including the Fourier, Cosine, Sine, Hartley, Laplace, Z, Mellin, Hankel, Radon, and Wavelet transforms—is a specific projection or specialization of a single **Universal Discrete Kernel Operator** \\( \\mathcal { K } _ { \\mathcal { G } _ N } [ n , k ] \\) defined over \\( \\mathcal { G } _ N \\):",
  "",
  "\\[ \\mathcal { K } _ { \\mathcal { G } _ N } [ n , k ] = r [ k ] ^ n \\left( \\cos \\left( \\frac { 2 \\pi n k } { N } \\right) + \\mathbf { I } \\sin \\left( \\frac { 2 \\pi n k } { N } \\right) \\right) \\]",
  "",
  "where \\( r [ k ] > 0 \\) is a real radial scaling factor, \\( \\theta _ k = \\frac { 2 \\pi k } { N } \\) is the discrete fundamental phase angle step, and \\( \\mathbf { I } \\) is an oriented unit bivector satisfying \\( \\mathbf { I } ^ 2 = - 1 \\).",
  "",
  "The unified transformation of a real analog or digital signal \\( x [ n ] \\) into its multivector spectral representation \\( \\hat { X } [ k ] \\) is given by the finite inner product on \\( \\mathcal { G } _ N \\):",
  "",
  "\\[ \\hat { X } [ k ] = \\sum _ { n = 0 } ^ { N - 1 } x [ n ] \\mathcal { K } _ { \\mathcal { G } _ N } [ n , k ] \\delta \\]",
  "",
  "==== Canonical Unification Mapping of Conventional Transforms",
  "",
  "1. **Discrete Fourier Transform (DFT) and Fourier Series**:",
  "   Setting \\( r [ k ] = 1 \\) for all \\( k \\) reduces the Universal Kernel to the pure phase rotor \\( \\mathcal { K } _ \\text{DFT} [ n , k ] = \\cos \\left( \\frac { 2 \\pi n k } { N } \\right) + \\mathbf { I } \\sin \\left( \\frac { 2 \\pi n k } { N } \\right) \\). The scalar component \\( \\operatorname { Sc } ( \\hat { X } [ k ] ) \\) isolates the even (cosine) harmonic spectrum, while the bivector component \\( \\operatorname { Biv } ( \\hat { X } [ k ] ) \\) isolates the odd (sine) harmonic spectrum.",
  "",
  "2. **Discrete Cosine Transform (DCT) and Discrete Sine Transform (DST)**:",
  "   Taking the real scalar projection \\( \\operatorname { Sc } ( \\mathcal { K } _ { \\mathcal { G } _ N } ) \\) or bivector projection \\( \\operatorname { Biv } ( \\mathcal { K } _ { \\mathcal { G } _ N } ) \\) under grid boundary shifts (e.g., half-step grid offsets \\( n \\to n + \\frac { 1 } { 2 } \\)) yields the standard discrete orthogonal cosine (DCT-II) and sine (DST-II) transforms:",
  "   \\[ X _ \\text{DCT} [ k ] = \\sum _ { n = 0 } ^ { N - 1 } x [ n ] \\cos \\left( \\frac { \\pi k ( 2 n + 1 ) } { 2 N } \\right) \\delta \\]",
  "   \\[ X _ \\text{DST} [ k ] = \\sum _ { n = 0 } ^ { N - 1 } x [ n ] \\sin \\left( \\frac { \\pi ( k + 1 ) ( 2 n + 1 ) } { 2 N } \\right) \\delta \\]",
  "",
  "3. **Hartley Transform**:",
  "   Summing the scalar and bivector components directly into a single real scalar value via the kernel operator \\( cas ( \\theta ) = \\cos \\theta + \\sin \\theta \\) yields the Hartley transform:",
  "   \\[ X _ \\text{Hartley} [ k ] = \\sum _ { n = 0 } ^ { N - 1 } x [ n ] \\left[ \\cos \\left( \\frac { 2 \\pi n k } { N } \\right) + \\sin \\left( \\frac { 2 \\pi n k } { N } \\right) \\right] \\delta \\]",
  "   Because \\( cas ( \\theta ) \\) is purely real and self-inverse, it performs complete spectral analysis without requiring bivector decomposition or complex algebra.",
  "",
  "4. **Laplace Transform**:",
  "   Generalizing the radial factor to represent real exponential spatial-temporal decay \\( r [ k ] = e ^ { - \\sigma [ k ] \\delta } \\) and angular phase precession \\( \\theta _ k = \\omega [ k ] \\delta \\) yields the Laplace transform kernel operator with \\( s = \\sigma + \\mathbf { I } \\omega \\):",
  "   \\[ \\mathcal { K } _ \\text{Laplace} ( t_n , s_k ) = e ^ { - s_k t_n } = e ^ { - \\sigma _ k t_n } \\left( \\cos ( \\omega _ k t_n ) - \\mathbf { I } \\sin ( \\omega _ k t_n ) \\right) \\]",
  "   This represents simultaneous physical energy dissipation into the surrounding grid lattice and bivector phase precession in real phase space.",
  "",
  "5. **Z-Transform**:",
  "   The discrete grid counterpart of the Laplace transform, where the discrete variable \\( z = r e ^ { \\mathbf { I } \\theta } = r ( \\cos \\theta + \\mathbf { I } \\sin \\theta ) \\) represents a real bivector rotor combined with a radial expansion or contraction factor \\( r \\). The inverse kernel \\( z ^ { - n } = r ^ { - n } ( \\cos ( n \\theta ) - \\mathbf { I } \\sin ( n \\theta ) ) \\) decomposes discrete time-series onto radial decay rings and angular precessions over \\( \\mathcal { G } _ N \\).",
  "",
  "6. **Mellin Transform**:",
  "   Mapping the spatial-temporal index logarithmically onto a discrete radial grid \\( n = e ^ u \\) transforms scale-dilation operators into linear phase shifts, yielding scale-invariant power spectrum analysis.",
  "",
  "7. **Hankel (Bessel) Transform**:",
  "   Representing the 2D spatial Fourier transform under rotational symmetry in a bivector plane \\( e _ 1 \\wedge e _ 2 \\). Integrating the bivector phase rotor over all polar angles \\( \\phi \\) yields real zero-order Bessel functions \\( J _ 0 ( k r ) \\) as orthogonal radial eigenfunctions over discrete circular apertures.",
  "",
  "8. **Radon Transform**:",
  "   Projecting 2D spatial mass or field distributions along directional line apertures on a 2D discrete grid \\( \\mathcal { G } _ N \\), mapping spatial structures into projection angles \\( \\theta \\) and radial offsets \\( s \\).",
  "",
  "9. **Wavelet Transform**:",
  "   Applying localized multiscale bandpass windowing \\( \\psi _ { a , b } [ n ] = \\frac { 1 } { \\sqrt { a } } \\psi \\left( \\frac { n \\delta - b } { a } \\right) \\) to the discrete kernel, providing joint spatial-temporal and spectral-resolution localization over multiscale grid tiers.",
  "",
  "10. **Hilbert Transform**:",
  "    Applying a quadrature phase-shift operator that rotates every bivector component by \\( 90 ^ \\circ \\) (multiplying by \\( \\mathbf { I } \\)), converting scalar cosine modes into bivector sine modes to generate analytic real signal pairs.",
  "",
  "11. **Homomorphic Cepstral Analysis**:",
  "    Evaluating the real natural logarithm of the bivector spectral magnitude \\( \\| \\hat { X } [ k ] \\| = \\sqrt { ( \\operatorname { Sc } ( \\hat { X } [ k ] ) ) ^ 2 + ( \\operatorname { Biv } ( \\hat { X } [ k ] ) ) ^ 2 } \\) yields a purely real logarithmic scalar sequence \\( L [ k ] = \\ln ( \\| \\hat { X } [ k ] \\| ) \\). Inverse-transforming \\( L [ k ] \\) back to the spatial-temporal grid via the real cosine kernel maps multiplicative system operations (such as lattice echo reflections or vocal tract filtering) into additive linear components in the discrete quefrency domain \\( q \\in \\mathcal { G } _ N \\), completely avoiding complex logarithms and multi-valued phase branch cuts."
].join("\n");

const sec3Content = [
  "=== Rigorous Proofs and Mathematical Theorems",
  "",
  "[#theorem-unified-real-bivector-spectral-transformation]",
  "[THEOREM]",
  ".Theorem: Unified Real-Bivector Spectral Transformation Theorem",
  "====",
  "Let \\( \\mathcal { G } _ N = \\{ n \\delta \\mid n \\in \\{ 0 , 1 , \\dots , N - 1 \\} \\} \\) be a finite discrete spatial-temporal resolution grid, and let \\( x [ n ] \\in \\mathbb { R } \\) be a real-valued digital or m-res signal.",
  "",
  "Every conventional linear integral and discrete transform (Fourier, Cosine, Sine, Hartley, Laplace, Z, Mellin, Hankel, Radon, and Wavelet) is an exact specialization or projection of the Universal Discrete Kernel Operator:",
  "\\[ \\mathcal { K } _ { \\mathcal { G } _ N } [ n , k ] = r [ k ] ^ n \\left( \\cos \\left( \\frac { 2 \\pi n k } { N } \\right) + \\mathbf { I } \\sin \\left( \\frac { 2 \\pi n k } { N } \\right) \\right) \\]",
  "where \\( r [ k ] > 0 \\) is a real radial scaling factor, \\( \\mathbf { I } \\) is a real unit bivector generator satisfying \\( \\mathbf { I } ^ 2 = - 1 \\), and no complex plane or imaginary numbers are required.",
  "",
  "*Proof:*",
  ". **Deconstruction of the Complex Imaginary Generator**:",
  "  In conventional analysis, the kernel is written as \\( e ^ { - i 2 \\pi n k / N } \\). In real Geometric Algebra \\( Cl ( 0 , 1 ) \\) or \\( Cl ( 2 , 0 ) \\), substitute \\( i \\to - \\mathbf { I } \\) where \\( \\mathbf { I } = e _ 1 e _ 2 \\). By Euler’s real geometric identity, \\( e ^ { - \\mathbf { I } \\theta } = \\cos \\theta - \\mathbf { I } \\sin \\theta \\). Every term in the expansion is a linear combination of a real scalar and a real oriented bivector.",
  "",
  ". **Constructive Derivation of Specializations**:",
  "  * **DFT**: Set \\( r [ k ] = 1 \\). Then \\( \\hat { X } [ k ] = \\sum _ { n = 0 } ^ { N - 1 } x [ n ] \\left( \\cos \\left( \\frac { 2 \\pi n k } { N } \\right) - \\mathbf { I } \\sin \\left( \\frac { 2 \\pi n k } { N } \\right) \\right) \\delta \\). Taking the scalar grade \\( \\operatorname { Sc } \\) yields the even cosine spectrum, and taking the bivector grade \\( \\operatorname { Biv } \\) yields the odd sine spectrum.",
  "  * **DCT and DST**: Projections \\( \\operatorname { Sc } ( \\mathcal { K } ) \\) and \\( \\operatorname { Biv } ( \\mathcal { K } ) \\) with grid boundary offset \\( n \\to n + \\frac { 1 } { 2 } \\).",
  "  * **Hartley**: Map the multivector sum \\( \\operatorname { Sc } ( \\mathcal { K } ) + \\mathbf { I } ^ { - 1 } \\operatorname { Biv } ( \\mathcal { K } ) \\to \\cos \\theta + \\sin \\theta = cas ( \\theta ) \\).",
  "  * **Laplace and Z-Transforms**: Set \\( r [ k ] = e ^ { - \\sigma [ k ] \\delta } \\). Then \\( r [ k ] ^ n e ^ { - \\mathbf { I } \\omega [ k ] n \\delta } = e ^ { - ( \\sigma [ k ] + \\mathbf { I } \\omega [ k ] ) n \\delta } = e ^ { - s_k t_n } \\). Setting \\( z_k = e ^ { s_k \\delta } = r [ k ] e ^ { \\mathbf { I } \\theta_k } \\) converts the kernel into \\( z_k ^ { - n } \\).",
  "  * **Mellin, Hankel, Radon, Wavelet**: Mapped by radial coordinate substitution \\( n = e ^ u \\), polar bivector integration \\( \\int _ 0 ^ { 2 \\pi } e ^ { - \\mathbf { I } k r \\cos \\phi } d \\phi = 2 \\pi J _ 0 ( k r ) \\), directional delta-line projections, and multiscale windowing \\( \\psi _ { a , b } [ n ] \\), respectively.",
  "",
  "All operations execute strictly over real scalars, real bivectors, and finite discrete grid sums on \\( \\mathcal { G } _ N \\), proving that complex numbers and continuum planes are completely redundant. \\( \\square \\)",
  "====",
  "",
  "[#theorem-discrete-orthogonality-parseval-energy-conservation]",
  "[THEOREM]",
  ".Theorem: Discrete Multiscale Orthogonality and Parseval-Plancherel Energy Conservation Theorem",
  "====",
  "On the discrete resolution grid \\( \\mathcal { G } _ N = \\{ n \\delta \\mid n \\in \\{ 0 , 1 , \\dots , N - 1 \\} \\} \\), the real bivector Fourier basis elements \\( \\mathcal { E } _ k [ n ] = \\frac { 1 } { \\sqrt { N } } \\left( \\cos \\left( \\frac { 2 \\pi n k } { N } \\right) + \\mathbf { I } \\sin \\left( \\frac { 2 \\pi n k } { N } \\right) \\right) \\) satisfy exact discrete orthogonality:",
  "",
  "\\[ \\sum _ { n = 0 } ^ { N - 1 } \\mathcal { E } _ k [ n ] \\mathcal { E } _ m ^ \\dagger [ n ] = \\delta _ { k , m } \\]",
  "",
  "where \\( \\dagger \\) denotes bivector reversion (\\( \\mathbf { I } ^ \\dagger = - \\mathbf { I } \\)). Furthermore, for any real signal \\( x [ n ] \\), total physical field energy is strictly conserved across domain representations:",
  "",
  "\\[ \\sum _ { n = 0 } ^ { N - 1 } ( x [ n ] ) ^ 2 = \\frac { 1 } { N } \\sum _ { k = 0 } ^ { N - 1 } \\left\\| \\hat { X } [ k ] \\right\\| ^ 2 \\]",
  "",
  "where \\( \\left\\| \\hat { X } [ k ] \\right\\| ^ 2 = \\left( \\operatorname { Sc } ( \\hat { X } [ k ] ) \\right) ^ 2 + \\left( \\operatorname { Biv } ( \\hat { X } [ k ] ) \\right) ^ 2 \\).",
  "",
  "*Proof:*",
  ". **Bivector Basis Orthogonality**:",
  "  Compute the bivector inner product sum for indices \\( k, m \\):",
  "  \\[ \\sum _ { n = 0 } ^ { N - 1 } \\mathcal { E } _ k [ n ] \\mathcal { E } _ m ^ \\dagger [ n ] = \\frac { 1 } { N } \\sum _ { n = 0 } ^ { N - 1 } \\left( \\cos \\frac { 2 \\pi n k } { N } + \\mathbf { I } \\sin \\frac { 2 \\pi n k } { N } \\right) \\left( \\cos \\frac { 2 \\pi n m } { N } - \\mathbf { I } \\sin \\frac { 2 \\pi n m } { N } \\right) \\]",
  "  Expanding the geometric product and using trigonometric product identities:",
  "  \\[ = \\frac { 1 } { N } \\sum _ { n = 0 } ^ { N - 1 } \\left[ \\cos \\left( \\frac { 2 \\pi n ( k - m ) } { N } \\right) + \\mathbf { I } \\sin \\left( \\frac { 2 \\pi n ( k - m ) } { N } \\right) \\right] \\]",
  "  For \\( k = m \\), every term equals \\( 1 + 0 = 1 \\), yielding \\( \\frac { 1 } { N } ( N ) = 1 \\).",
  "  For \\( k \\neq m \\), the sum is a finite geometric series of non-zero phase rotations over a complete period, summing identically to zero. Thus, \\( \\sum _ { n = 0 } ^ { N - 1 } \\mathcal { E } _ k [ n ] \\mathcal { E } _ m ^ \\dagger [ n ] = \\delta _ { k , m } \\).",
  "",
  ". **Energy Conservation**:",
  "  Express \\( x [ n ] \\) in terms of its orthogonal spectral expansion \\( x [ n ] = \\frac { 1 } { \\sqrt { N } } \\sum _ { k = 0 } ^ { N - 1 } \\hat { X } [ k ] \\mathcal { E } _ k [ n ] \\). Computing the sum of squares \\( \\sum _ { n = 0 } ^ { N - 1 } ( x [ n ] ) ^ 2 \\) and substituting the basis orthogonality relation directly yields \\( \\frac { 1 } { N } \\sum _ { k = 0 } ^ { N - 1 } \\| \\hat { X } [ k ] \\| ^ 2 \\). This proves exact Parseval-Plancherel energy conservation strictly within finite discrete sums on \\( \\mathcal { G } _ N \\). \\( \\square \\)",
  "====",
  "",
  "[#theorem-z-laplace-isomorphism-discrete-decay]",
  "[THEOREM]",
  ".Theorem: Isomorphism of Discrete Z-Transform and Damped Bivector Phase Precession Theorem",
  "====",
  "Let \\( s = \\sigma + \\mathbf { I } \\omega \\) be the continuous-domain damped bivector Laplace operator in \\( Cl ( 0 , 1 ) \\), where \\( \\sigma \\in \\mathbb { R } \\) is the lattice attenuation coefficient and \\( \\omega \\in \\mathbb { R } \\) is the angular phase velocity.",
  "",
  "Under spatial-temporal sampling on discrete resolution grid \\( \\mathcal { G } _ N \\) with step spacing \\( \\delta \\), the Laplace transform operator \\( e ^ { - s n \\delta } \\) is algebraically isomorphic to the discrete Z-transform operator \\( z ^ { - n } \\) under the exact discrete mapping:",
  "",
  "\\[ z = e ^ { s \\delta } = r e ^ { \\mathbf { I } \\theta } \\]",
  "where the discrete radial expansion factor is \\( r = e ^ { \\sigma \\delta } \\) and the discrete phase step angle is \\( \\theta = \\omega \\delta \\).",
  "",
  "*Proof:*",
  ". **Expansion of Laplace Kernel**:",
  "  Evaluate the Laplace kernel at discrete time step \\( t_n = n \\delta \\):",
  "  \\[ e ^ { - s t_n } = e ^ { - ( \\sigma + \\mathbf { I } \\omega ) n \\delta } = e ^ { - \\sigma n \\delta } e ^ { - \\mathbf { I } \\omega n \\delta } \\]",
  "  Applying real Euler bivector decomposition:",
  "  \\[ = ( e ^ { \\sigma \\delta } ) ^ { - n } \\left( \\cos ( n \\omega \\delta ) - \\mathbf { I } \\sin ( n \\omega \\delta ) \\right) \\]",
  "",
  ". **Algebraic Substitution**:",
  "  Define \\( r = e ^ { \\sigma \\delta } > 0 \\) and \\( \\theta = \\omega \\delta \\in [ - \\pi , \\pi ) \\). The bivector number \\( z \\in Cl ( 0 , 1 ) \\) is:",
  "  \\[ z = r e ^ { \\mathbf { I } \\theta } = r ( \\cos \\theta + \\mathbf { I } \\sin \\theta ) \\]",
  "  Raising \\( z \\) to the negative power \\( - n \\) by De Moivre's real bivector theorem yields:",
  "  \\[ z ^ { - n } = r ^ { - n } ( \\cos ( n \\theta ) - \\mathbf { I } \\sin ( n \\theta ) ) = e ^ { - \\sigma n \\delta } e ^ { - \\mathbf { I } \\omega n \\delta } = e ^ { - s n \\delta } \\]",
  "  This establishes an exact, bijective algebraic isomorphism between the damped bivector Laplace operator and the discrete Z-transform operator on grid \\( \\mathcal { G } _ N \\). \\( \\square \\)",
  "===="
].join("\n");

const sec4Content = [
  "=== Completely Worked Textbook Examples",
  "",
  "==== Example 1: Real Bivector Discrete Fourier Spectrum and Energy Conservation on \\( \\mathcal { G } _ 4 \\)",
  "",
  "**Problem Statement:**",
  "Given a real digital spatial-temporal signal sequence \\( x [ n ] = [ 1 , 1 , 0 , 0 ] ^ T \\) defined on the 4-point resolution grid \\( \\mathcal { G } _ 4 = \\{ 0 , 1 , 2 , 3 \\} \\) with grid spacing \\( \\delta = 1 \\):",
  "1. Compute the multivector Discrete Fourier Spectrum \\( \\hat { X } [ k ] \\) for all harmonic modes \\( k \\in \\{ 0 , 1 , 2 , 3 \\} \\) using the real bivector rotor kernel:",
  "   \\[ \\mathcal { K } _ \\text{DFT} [ n , k ] = \\cos \\left( \\frac { 2 \\pi n k } { 4 } \\right) - \\mathbf { I } \\sin \\left( \\frac { 2 \\pi n k } { 4 } \\right) \\]",
  "   where \\( \\mathbf { I } \\) is the unit bivector in \\( Cl ( 0 , 1 ) \\) satisfying \\( \\mathbf { I } ^ 2 = - 1 \\).",
  "2. Explicitly verify the Parseval-Plancherel energy conservation theorem between physical space and real bivector phase space.",
  "",
  "**Step-by-Step Solution:**",
  "* **Harmonic Mode \\( k = 0 \\)**:",
  "  The kernel evaluates to \\( \\mathcal { K } _ \\text{DFT} [ n , 0 ] = \\cos ( 0 ) - \\mathbf { I } \\sin ( 0 ) = 1 \\) for all \\( n \\).",
  "  \\[ \\hat { X } [ 0 ] = \\sum _ { n = 0 } ^ { 3 } x [ n ] ( 1 ) = 1 + 1 + 0 + 0 = 2 \\]",
  "  This is a pure scalar grade multivector (\\( \\operatorname { Sc } = 2, \\operatorname { Biv } = 0 \\)), representing the DC bias / total spatial field sum.",
  "",
  "* **Harmonic Mode \\( k = 1 \\)**:",
  "  The fundamental phase step angle is \\( \\theta = \\frac { 2 \\pi ( 1 ) } { 4 } = \\frac { \\pi } { 2 } \\). Evaluating the kernel for each grid point \\( n \\):",
  "  - \\( n = 0 \\): \\( \\mathcal { K } [ 0 , 1 ] = \\cos ( 0 ) - \\mathbf { I } \\sin ( 0 ) = 1 \\)",
  "  - \\( n = 1 \\): \\( \\mathcal { K } [ 1 , 1 ] = \\cos \\left( \\frac { \\pi } { 2 } \\right) - \\mathbf { I } \\sin \\left( \\frac { \\pi } { 2 } \\right) = - \\mathbf { I } \\)",
  "  - \\( n = 2 \\): \\( \\mathcal { K } [ 2 , 1 ] = \\cos ( \\pi ) - \\mathbf { I } \\sin ( \\pi ) = - 1 \\)",
  "  - \\( n = 3 \\): \\( \\mathcal { K } [ 3 , 1 ] = \\cos \\left( \\frac { 3 \\pi } { 2 } \\right) - \\mathbf { I } \\sin \\left( \\frac { 3 \\pi } { 2 } \\right) = \\mathbf { I } \\)",
  "  Computing the finite inner product over \\( \\mathcal { G } _ 4 \\):",
  "  \\[ \\hat { X } [ 1 ] = ( 1 ) ( 1 ) + ( 1 ) ( - \\mathbf { I } ) + ( 0 ) ( - 1 ) + ( 0 ) ( \\mathbf { I } ) = 1 - \\mathbf { I } \\]",
  "  The scalar component is \\( \\operatorname { Sc } = 1 \\) and the bivector component is \\( \\operatorname { Biv } = - 1 \\).",
  "",
  "* **Harmonic Mode \\( k = 2 \\)**:",
  "  The phase step angle is \\( \\theta = \\pi \\). Evaluating the kernel for each grid point \\( n \\):",
  "  - \\( n = 0 \\): \\( \\mathcal { K } [ 0 , 2 ] = 1 \\)",
  "  - \\( n = 1 \\): \\( \\mathcal { K } [ 1 , 2 ] = \\cos ( \\pi ) - \\mathbf { I } \\sin ( \\pi ) = - 1 \\)",
  "  - \\( n = 2 \\): \\( \\mathcal { K } [ 2 , 2 ] = \\cos ( 2 \\pi ) - \\mathbf { I } \\sin ( 2 \\pi ) = 1 \\)",
  "  - \\( n = 3 \\): \\( \\mathcal { K } [ 3 , 2 ] = \\cos ( 3 \\pi ) - \\mathbf { I } \\sin ( 3 \\pi ) = - 1 \\)",
  "  Computing the finite inner product:",
  "  \\[ \\hat { X } [ 2 ] = ( 1 ) ( 1 ) + ( 1 ) ( - 1 ) + ( 0 ) ( 1 ) + ( 0 ) ( - 1 ) = 0 \\]",
  "",
  "* **Harmonic Mode \\( k = 3 \\)**:",
  "  The phase step angle is \\( \\theta = \\frac { 3 \\pi } { 2 } \\). Evaluating the kernel for each grid point \\( n \\):",
  "  - \\( n = 0 \\): \\( \\mathcal { K } [ 0 , 3 ] = 1 \\)",
  "  - \\( n = 1 \\): \\( \\mathcal { K } [ 1 , 3 ] = \\cos \\left( \\frac { 3 \\pi } { 2 } \\right) - \\mathbf { I } \\sin \\left( \\frac { 3 \\pi } { 2 } \\right) = \\mathbf { I } \\)",
  "  - \\( n = 2 \\): \\( \\mathcal { K } [ 2 , 3 ] = - 1 \\)",
  "  - \\( n = 3 \\): \\( \\mathcal { K } [ 3 , 3 ] = - \\mathbf { I } \\)",
  "  Computing the finite inner product:",
  "  \\[ \\hat { X } [ 3 ] = ( 1 ) ( 1 ) + ( 1 ) ( \\mathbf { I } ) + ( 0 ) ( - 1 ) + ( 0 ) ( - \\mathbf { I } ) = 1 + \\mathbf { I } \\]",
  "",
  "* **Verification of Parseval-Plancherel Energy Conservation**:",
  "  In physical spatial grid space, computing total field energy:",
  "  \\[ E _ \\text{grid} = \\sum _ { n = 0 } ^ { 3 } ( x [ n ] ) ^ 2 = ( 1 ) ^ 2 + ( 1 ) ^ 2 + ( 0 ) ^ 2 + ( 0 ) ^ 2 = 2 \\]",
  "  In real bivector spectral space, computing the multivector norm squared \\( \\| \\hat { X } [ k ] \\| ^ 2 = ( \\operatorname { Sc } ( \\hat { X } [ k ] ) ) ^ 2 + ( \\operatorname { Biv } ( \\hat { X } [ k ] ) ) ^ 2 \\):",
  "  - \\( \\| \\hat { X } [ 0 ] \\| ^ 2 = 2 ^ 2 + 0 ^ 2 = 4 \\)",
  "  - \\( \\| \\hat { X } [ 1 ] \\| ^ 2 = 1 ^ 2 + ( - 1 ) ^ 2 = 2 \\)",
  "  - \\( \\| \\hat { X } [ 2 ] \\| ^ 2 = 0 ^ 2 + 0 ^ 2 = 0 \\)",
  "  - \\( \\| \\hat { X } [ 3 ] \\| ^ 2 = 1 ^ 2 + 1 ^ 2 = 2 \\)",
  "  Summing spectral energy terms:",
  "  \\[ E _ \\text{spectral} = \\frac { 1 } { 4 } \\sum _ { k = 0 } ^ { 3 } \\| \\hat { X } [ k ] \\| ^ 2 = \\frac { 1 } { 4 } ( 4 + 2 + 0 + 2 ) = \\frac { 8 } { 4 } = 2 \\]",
  "  Thus, \\( E _ \\text{grid} = E _ \\text{spectral} = 2 \\), confirming exact discrete energy conservation.",
  "",
  "==== Example 2: Discrete Cosine Transform (DCT-II) and Discrete Hartley Transform (DHT) on \\( \\mathcal { G } _ 4 \\)",
  "",
  "**Problem Statement:**",
  "For the real digital physical signal \\( x [ n ] = [ 4 , 2 , 1 , 0 ] ^ T \\) on \\( \\mathcal { G } _ 4 \\):",
  "1. Compute the discrete orthogonal Cosine Transform (DCT-II) sequence \\( X _ \\text{DCT} [ k ] \\) for \\( k \\in \\{ 0 , 1 , 2 , 3 \\} \\):",
  "   \\[ X _ \\text{DCT} [ k ] = \\sum _ { n = 0 } ^ { 3 } x [ n ] \\cos \\left( \\frac { \\pi k ( 2 n + 1 ) } { 8 } \\right) \\]",
  "2. Compute the Discrete Hartley Transform (DHT) sequence \\( X _ \\text{DHT} [ k ] \\) using the purely real scalar kernel \\( cas ( \\theta ) = \\cos \\theta + \\sin \\theta \\):",
  "   \\[ X _ \\text{DHT} [ k ] = \\sum _ { n = 0 } ^ { 3 } x [ n ] \\left[ \\cos \\left( \\frac { 2 \\pi n k } { 4 } \\right) + \\sin \\left( \\frac { 2 \\pi n k } { 4 } \\right) \\right] \\]",
  "3. Demonstrate that both transforms execute strictly over real physical scalar channels without complex numbers or bivector allocations.",
  "",
  "**Step-by-Step Solution:**",
  "* **Part 1: DCT-II Computation**:",
  "  Evaluating kernel angles \\( \\theta _ { n , k } = \\frac { \\pi k ( 2 n + 1 ) } { 8 } \\):",
  "  - **\\( k = 0 \\)**: \\( \\cos ( 0 ) = 1 \\) for all \\( n \\).",
  "    \\[ X _ \\text{DCT} [ 0 ] = 4 ( 1 ) + 2 ( 1 ) + 1 ( 1 ) + 0 ( 1 ) = 7 \\]",
  "  - **\\( k = 1 \\)**: Angles are \\( \\frac { \\pi } { 8 } , \\frac { 3 \\pi } { 8 } , \\frac { 5 \\pi } { 8 } , \\frac { 7 \\pi } { 8 } \\).",
  "    Values: \\( \\cos \\left( \\frac { \\pi } { 8 } \\right) \\approx 0.92388 \\), \\( \\cos \\left( \\frac { 3 \\pi } { 8 } \\right) \\approx 0.38268 \\), \\( \\cos \\left( \\frac { 5 \\pi } { 8 } \\right) = - 0.38268 \\), \\( \\cos \\left( \\frac { 7 \\pi } { 8 } \\right) = - 0.92388 \\).",
  "    \\[ X _ \\text{DCT} [ 1 ] = 4 ( 0.92388 ) + 2 ( 0.38268 ) + 1 ( - 0.38268 ) + 0 ( - 0.92388 ) = 4.07820 \\]",
  "  - **\\( k = 2 \\)**: Angles are \\( \\frac { \\pi } { 4 } , \\frac { 3 \\pi } { 4 } , \\frac { 5 \\pi } { 4 } , \\frac { 7 \\pi } { 4 } \\).",
  "    Values: \\( \\frac { \\sqrt { 2 } } { 2 } , - \\frac { \\sqrt { 2 } } { 2 } , - \\frac { \\sqrt { 2 } } { 2 } , \\frac { \\sqrt { 2 } } { 2 } \\approx 0.70711 \\).",
  "    \\[ X _ \\text{DCT} [ 2 ] = ( 4 - 2 - 1 + 0 ) \\frac { \\sqrt { 2 } } { 2 } = \\frac { \\sqrt { 2 } } { 2 } \\approx 0.70711 \\]",
  "  - **\\( k = 3 \\)**: Angles are \\( \\frac { 3 \\pi } { 8 } , \\frac { 9 \\pi } { 8 } , \\frac { 15 \\pi } { 8 } , \\frac { 21 \\pi } { 8 } \\).",
  "    Values: \\( \\cos \\left( \\frac { 3 \\pi } { 8 } \\right) \\approx 0.38268 \\), \\( \\cos \\left( \\frac { 9 \\pi } { 8 } \\right) \\approx - 0.92388 \\), \\( \\cos \\left( \\frac { 15 \\pi } { 8 } \\right) \\approx 0.92388 \\), \\( \\cos \\left( \\frac { 21 \\pi } { 8 } \\right) \\approx - 0.38268 \\).",
  "    \\[ X _ \\text{DCT} [ 3 ] = 4 ( 0.38268 ) + 2 ( - 0.92388 ) + 1 ( 0.92388 ) + 0 = 0.60684 \\]",
  "",
  "* **Part 2: Hartley Transform (DHT) Computation**:",
  "  Evaluating kernel \\( cas \\left( \\frac { 2 \\pi n k } { 4 } \\right) = \\cos \\left( \\frac { \\pi n k } { 2 } \\right) + \\sin \\left( \\frac { \\pi n k } { 2 } \\right) \\):",
  "  - **\\( k = 0 \\)**: \\( cas ( 0 ) = 1 \\).",
  "    \\[ X _ \\text{DHT} [ 0 ] = 4 ( 1 ) + 2 ( 1 ) + 1 ( 1 ) + 0 ( 1 ) = 7 \\]",
  "  - **\\( k = 1 \\)**: Kernel values for \\( n = 0, 1, 2, 3 \\) are \\( 1, 1, - 1, - 1 \\).",
  "    \\[ X _ \\text{DHT} [ 1 ] = 4 ( 1 ) + 2 ( 1 ) + 1 ( - 1 ) + 0 ( - 1 ) = 5 \\]",
  "  - **\\( k = 2 \\)**: Kernel values for \\( n = 0, 1, 2, 3 \\) are \\( 1, - 1, 1, - 1 \\).",
  "    \\[ X _ \\text{DHT} [ 2 ] = 4 ( 1 ) + 2 ( - 1 ) + 1 ( 1 ) + 0 ( - 1 ) = 3 \\]",
  "  - **\\( k = 3 \\)**: Kernel values for \\( n = 0, 1, 2, 3 \\) are \\( 1, - 1, - 1, 1 \\).",
  "    \\[ X _ \\text{DHT} [ 3 ] = 4 ( 1 ) + 2 ( - 1 ) + 1 ( - 1 ) + 0 ( 1 ) = 1 \\]",
  "  The Hartley transform produces the exact real integer spectral vector \\( X _ \\text{DHT} = [ 7 , 5 , 3 , 1 ] ^ T \\) without complex or bivector variables.",
  "",
  "==== Example 3: Discrete Z-Transform and Damped Bivector Phase Precession",
  "",
  "**Problem Statement:**",
  "Consider a real decaying digital signal \\( x [ n ] = \\left( \\frac { 1 } { 2 } \\right) ^ n \\) defined over the 4-point spatial-temporal grid \\( \\mathcal { G } _ 4 = \\{ 0 , 1 , 2 , 3 \\} \\).",
  "1. Formulate the general digital multivector Z-transform \\( X ( z ) \\) over \\( \\mathcal { G } _ 4 \\):",
  "   \\[ X ( z ) = \\sum _ { n = 0 } ^ { 3 } x [ n ] z ^ { - n } \\]",
  "   where \\( z = r e ^ { \\mathbf { I } \\theta } = r ( \\cos \\theta + \\mathbf { I } \\sin \\theta ) \\) is a real bivector rotor in \\( Cl ( 0 , 1 ) \\).",
  "2. Completely evaluate \\( X ( z ) \\) at the specific bivector phase rotor location \\( z = 2 e ^ { \\mathbf { I } \\pi / 2 } = 2 \\mathbf { I } \\) (corresponding to radial expansion factor \\( r = 2 \\) and phase angle step \\( \\theta = \\frac { \\pi } { 2 } \\)).",
  "",
  "**Step-by-Step Solution:**",
  "* **General Multivector Expansion**:",
  "  Given \\( x [ n ] = \\left[ 1 , \\frac { 1 } { 2 } , \\frac { 1 } { 4 } , \\frac { 1 } { 8 } \\right] ^ T \\):",
  "  \\[ X ( z ) = 1 + \\frac { 1 } { 2 } z ^ { - 1 } + \\frac { 1 } { 4 } z ^ { - 2 } + \\frac { 1 } { 8 } z ^ { - 3 } \\]",
  "",
  "* **Evaluating Powers of Bivector Rotor \\( z = 2 \\mathbf { I } \\)**:",
  "  Using the fundamental bivector identity \\( \\mathbf { I } ^ 2 = - 1 \\):",
  "  - \\( z ^ 0 = 1 \\)",
  "  - \\( z ^ 1 = 2 \\mathbf { I } \\implies z ^ { - 1 } = \\frac { 1 } { 2 \\mathbf { I } } = - \\frac { 1 } { 2 } \\mathbf { I } \\)",
  "  - \\( z ^ 2 = ( 2 \\mathbf { I } ) ^ 2 = - 4 \\implies z ^ { - 2 } = - \\frac { 1 } { 4 } \\)",
  "  - \\( z ^ 3 = ( 2 \\mathbf { I } ) ( - 4 ) = - 8 \\mathbf { I } \\implies z ^ { - 3 } = \\frac { 1 } { 8 } \\mathbf { I } \\)",
  "",
  "* **Substituting Powers into \\( X ( z ) \\)**:",
  "  - Term \\( n = 0 \\): \\( ( 1 ) ( 1 ) = 1 \\)",
  "  - Term \\( n = 1 \\): \\( \\left( \\frac { 1 } { 2 } \\right) \\left( - \\frac { 1 } { 2 } \\mathbf { I } \\right) = - \\frac { 1 } { 4 } \\mathbf { I } \\)",
  "  - Term \\( n = 2 \\): \\( \\left( \\frac { 1 } { 4 } \\right) \\left( - \\frac { 1 } { 4 } \\right) = - \\frac { 1 } { 16 } \\)",
  "  - Term \\( n = 3 \\): \\( \\left( \\frac { 1 } { 8 } \\right) \\left( \\frac { 1 } { 8 } \\mathbf { I } \\right) = \\frac { 1 } { 64 } \\mathbf { I } \\)",
  "",
  "* **Summing Scalar and Bivector Components**:",
  "  Combining terms into grade components:",
  "  \\[ X ( 2 \\mathbf { I } ) = \\left( 1 - \\frac { 1 } { 16 } \\right) + \\mathbf { I } \\left( - \\frac { 1 } { 4 } + \\frac { 1 } { 64 } \\right) \\]",
  "  - Scalar grade: \\( \\operatorname { Sc } = \\frac { 15 } { 16 } = 0.9375 \\)",
  "  - Bivector grade: \\( \\operatorname { Biv } = - \\frac { 16 } { 64 } + \\frac { 1 } { 64 } = - \\frac { 15 } { 64 } = - 0.234375 \\)",
  "",
  "  Thus, the exact multivector Z-transform evaluation is:",
  "  \\[ X ( 2 \\mathbf { I } ) = \\frac { 15 } { 16 } - \\frac { 15 } { 64 } \\mathbf { I } \\]",
  "  This represents a real scalar field amplitude of \\( 0.9375 \\) combined with an orthogonal bivector phase component of \\( - 0.234375 \\), computed directly without continuous complex numbers.",
  "",
  "==== Example 4: Real Homomorphic Cepstrum and Echo Deconvolution on \\( \\mathcal { G } _ 4 \\)",
  "",
  "**Problem Statement:**",
  "Consider a real digital physical signal sequence \\( x [ n ] = [ 4 , 1 , 2 , 1 ] ^ T \\) defined on the 4-point spatial-temporal grid \\( \\mathcal { G } _ 4 = \\{ 0 , 1 , 2 , 3 \\} \\).",
  "1. Compute the multivector Discrete Fourier Spectrum \\( \\hat { X } [ k ] \\) and the corresponding real spectral magnitudes \\( \\| \\hat { X } [ k ] \\| \\) for all harmonic modes \\( k \\in \\{ 0 , 1 , 2 , 3 \\} \\).",
  "2. Evaluate the real logarithmic spectral magnitude sequence \\( L [ k ] = \\ln ( \\| \\hat { X } [ k ] \\| ) \\).",
  "3. Compute the Real Homomorphic Cepstrum sequence \\( c [ q ] \\) for all discrete quefrency indices \\( q \\in \\{ 0 , 1 , 2 , 3 \\} \\) using the real inverse cosine kernel:",
  "   \\[ c [ q ] = \\frac { 1 } { 4 } \\sum _ { k = 0 } ^ { 3 } L [ k ] \\cos \\left( \\frac { 2 \\pi k q } { 4 } \\right) \\]",
  "",
  "**Step-by-Step Solution:**",
  "* **Step 1: Multivector Fourier Spectrum and Spectral Magnitudes**:",
  "  Computing \\( \\hat { X } [ k ] = \\sum _ { n = 0 } ^ { 3 } x [ n ] \\left( \\cos \\left( \\frac { 2 \\pi n k } { 4 } \\right) - \\mathbf { I } \\sin \\left( \\frac { 2 \\pi n k } { 4 } \\right) \\right) \\):",
  "  - \\( k = 0 \\): \\( \\hat { X } [ 0 ] = 4 + 1 + 2 + 1 = 8 + 0 \\mathbf { I } \\implies \\| \\hat { X } [ 0 ] \\| = 8 \\)",
  "  - \\( k = 1 \\): \\( \\hat { X } [ 1 ] = 4 ( 1 ) + 1 ( - \\mathbf { I } ) + 2 ( - 1 ) + 1 ( \\mathbf { I } ) = 2 + 0 \\mathbf { I } \\implies \\| \\hat { X } [ 1 ] \\| = 2 \\)",
  "  - \\( k = 2 \\): \\( \\hat { X } [ 2 ] = 4 ( 1 ) + 1 ( - 1 ) + 2 ( 1 ) + 1 ( - 1 ) = 4 + 0 \\mathbf { I } \\implies \\| \\hat { X } [ 2 ] \\| = 4 \\)",
  "  - \\( k = 3 \\): \\( \\hat { X } [ 3 ] = 4 ( 1 ) + 1 ( \\mathbf { I } ) + 2 ( - 1 ) + 1 ( - \\mathbf { I } ) = 2 + 0 \\mathbf { I } \\implies \\| \\hat { X } [ 3 ] \\| = 2 \\)",
  "",
  "* **Step 2: Real Logarithmic Spectral Magnitude Sequence \\( L [ k ] \\)**:",
  "  Taking the natural logarithm of each spectral magnitude:",
  "  - \\( L [ 0 ] = \\ln ( 8 ) = 3 \\ln 2 \\)",
  "  - \\( L [ 1 ] = \\ln ( 2 ) = \\ln 2 \\)",
  "  - \\( L [ 2 ] = \\ln ( 4 ) = 2 \\ln 2 \\)",
  "  - \\( L [ 3 ] = \\ln ( 2 ) = \\ln 2 \\)",
  "",
  "* **Step 3: Real Homomorphic Cepstrum Computation \\( c [ q ] \\)**:",
  "  Applying the real inverse cosine kernel \\( c [ q ] = \\frac { 1 } { 4 } \\sum _ { k = 0 } ^ { 3 } L [ k ] \\cos \\left( \\frac { \\pi k q } { 2 } \\right) \\):",
  "  - **Quefrency \\( q = 0 \\)**:",
  "    Cosine terms for \\( k \\in \\{ 0 , 1 , 2 , 3 \\} \\) are all \\( 1 \\).",
  "    \\[ c [ 0 ] = \\frac { 1 } { 4 } ( 3 \\ln 2 + \\ln 2 + 2 \\ln 2 + \\ln 2 ) = \\frac { 7 } { 4 } \\ln 2 \\approx 1.21299 \\]",
  "  - **Quefrency \\( q = 1 \\)**:",
  "    Cosine terms are \\( \\cos ( 0 ) = 1, \\cos \\left( \\frac { \\pi } { 2 } \\right) = 0, \\cos ( \\pi ) = - 1, \\cos \\left( \\frac { 3 \\pi } { 2 } \\right) = 0 \\).",
  "    \\[ c [ 1 ] = \\frac { 1 } { 4 } ( L [ 0 ] ( 1 ) + L [ 1 ] ( 0 ) + L [ 2 ] ( - 1 ) + L [ 3 ] ( 0 ) ) = \\frac { 1 } { 4 } ( 3 \\ln 2 - 2 \\ln 2 ) = \\frac { 1 } { 4 } \\ln 2 \\approx 0.17329 \\]",
  "  - **Quefrency \\( q = 2 \\)**:",
  "    Cosine terms are \\( \\cos ( 0 ) = 1, \\cos ( \\pi ) = - 1, \\cos ( 2 \\pi ) = 1, \\cos ( 3 \\pi ) = - 1 \\).",
  "    \\[ c [ 2 ] = \\frac { 1 } { 4 } ( 3 \\ln 2 - \\ln 2 + 2 \\ln 2 - \\ln 2 ) = \\frac { 3 } { 4 } \\ln 2 \\approx 0.51986 \\]",
  "  - **Quefrency \\( q = 3 \\)**:",
  "    Cosine terms are \\( \\cos ( 0 ) = 1, \\cos \\left( \\frac { 3 \\pi } { 2 } \\right) = 0, \\cos ( 3 \\pi ) = - 1, \\cos \\left( \\frac { 9 \\pi } { 2 } \\right) = 0 \\).",
  "    \\[ c [ 3 ] = \\frac { 1 } { 4 } ( L [ 0 ] ( 1 ) + L [ 1 ] ( 0 ) + L [ 2 ] ( - 1 ) + L [ 3 ] ( 0 ) ) = \\frac { 1 } { 4 } ( 3 \\ln 2 - 2 \\ln 2 ) = \\frac { 1 } { 4 } \\ln 2 \\approx 0.17329 \\]",
  "",
  "  The resulting real homomorphic cepstrum vector is \\( c [ q ] = \\left[ \\frac { 7 } { 4 } \\ln 2 , \\frac { 1 } { 4 } \\ln 2 , \\frac { 3 } { 4 } \\ln 2 , \\frac { 1 } { 4 } \\ln 2 \\right] ^ T \\). All calculations execute over purely real scalars in discrete quefrency space without complex analysis."
].join("\n");

const chap2Sec1Content = [
  "=== m-Resolution Analog and Digital System Paradigms",
  "",
  "In 19th and 20th-century classical linear system theory, physical engineering was conventionally split into two disjoint domains: analog signals (conventionally mislabeled as “continuous-time signals”) operating over an uncountably infinite real continuum, and digital signals (conventionally called “discrete-time signals”) operating over sampled integer sequences. Conventional analog models relied on non-physical Dirac delta distributions \\( \\delta ( t ) \\), which were imagined to possess zero spatial-temporal width, infinite amplitude at the origin, and a unit area integral. In actual physical Nature, there exist no point entities of infinite amplitude or zero temporal duration; all physical excitations, wave propagations, and field responses require finite time and possess finite spatial extent.",
  "",
  "In the Iris Number System, physical system dynamics and signals are formulated entirely on discrete resolution grids \\( \\mathcal { G } _ N \\):",
  "",
  "1. **The m-Resolution Analog Signal Grid Representation**:",
  "   Physical analog signals (m-res signals) occur on a fine m-resolution grid \\( \\mathcal { G } _ { N , m } = \\{ n \\delta _ m \\mid n \\in \\{ 0 , 1 , \\dots , N - 1 \\} \\} \\) with fine lattice spacing \\( \\delta _ m > 0 \\). On this physical grid, the m-resolution unit impulse excitation \\( \\delta _ { \\mathcal { G } _ m } [ n ] \\) is defined as a finite, unit-energy pulse of width \\( \\delta _ m \\):",
  "   \\[ \\delta _ { \\mathcal { G } _ m } [ n ] = \\begin {cases} \\frac { 1 } { \\delta _ m } , & n = 0 \\\\ 0 , & n \\neq 0 \\end {cases} \\]",
  "   satisfying the exact discrete field summation \\( \\sum _ { n = 0 } ^ { N - 1 } \\delta _ { \\mathcal { G } _ m } [ n ] \\delta _ m = 1 \\). This impulse represents a finite physical excitation delivered over finite duration \\( \\delta _ m \\) with peak amplitude \\( 1 / \\delta _ m \\), completely removing Dirac point infinities.",
  "",
  "2. **The Digital Signal Grid Representation**:",
  "   Algorithmic digital signals operate on a coarser digital grid \\( \\mathcal { G } _ D = \\{ k \\Delta t \\mid k \\in \\{ 0 , 1 , \\dots , K - 1 \\} \\} \\) with sampling interval \\( \\Delta t = M \\delta _ m \\) (where \\( M \\in \\mathbb { Z } ^ + \\)). On the digital grid, the digital unit impulse \\( \\delta [ k ] \\) is the discrete Kronecker delta:",
  "   \\[ \\delta [ k ] = \\begin {cases} 1 , & k = 0 \\\\ 0 , & k \\neq 0 \\end {cases} \\]",
  "   Both m-resolution analog signals and digital signals are represented on finite resolution grids, differing only in resolution scale \\( \\delta _ m \\) versus \\( \\Delta t \\)."
].join("\n");

const chap2Sec2Content = [
  "=== Shift-Invariant Systems, Difference Convolution, and Bivector Transfer Functions",
  "",
  "Consider a Linear Shift-Invariant (LSI) physical system operator \\( \\mathcal { S } \\) mapping an input signal sequence \\( x [ n ] \\) on resolution grid \\( \\mathcal { G } _ N \\) to an output response signal \\( y [ n ] \\).",
  "",
  "==== The Unit Impulse Response and Finite Convolution Sum",
  "The system \\( \\mathcal { S } \\) is uniquely characterized by its unit impulse response sequence \\( h [ n ] = \\mathcal { S } \\{ \\delta _ { \\mathcal { G } } [ n ] \\} \\). By linear superposition and shift-invariance, any analog or digital input signal \\( x [ n ] \\) can be decomposed into a linear sum of shifted impulses \\( x [ n ] = \\sum _ { m = 0 } ^ { N - 1 } x [ m ] \\delta _ { \\mathcal { G } } [ n - m ] \\delta \\). The system output is given by the finite difference convolution sum over \\( \\mathcal { G } _ N \\):",
  "",
  "\\[ y [ n ] = ( x * h ) [ n ] = \\sum _ { m = 0 } ^ { N - 1 } x [ m ] h [ n - m ] \\delta \\]",
  "",
  "==== Eigenfunction Property and System Transfer Function",
  "To determine the frequency-domain response of \\( \\mathcal { S } \\), excite the system with the real bivector exponential sequence \\( x [ n ] = e ^ { s n \\delta } \\), where \\( s = \\sigma + \\mathbf { I } \\omega \\in Cl ( 0 , 1 ) \\) is the damped bivector Laplace variable with attenuation factor \\( \\sigma \\in \\mathbb { R } \\), phase angular velocity \\( \\omega \\in \\mathbb { R } \\), and oriented unit bivector generator \\( \\mathbf { I } \\) satisfying \\( \\mathbf { I } ^ 2 = - 1 \\).",
  "",
  "Substituting \\( x [ n ] = e ^ { s n \\delta } \\) into the convolution sum yields:",
  "\\[ y [ n ] = \\sum _ { m = 0 } ^ { N - 1 } e ^ { s ( n - m ) \\delta } h [ m ] \\delta = e ^ { s n \\delta } \\left( \\sum _ { m = 0 } ^ { N - 1 } h [ m ] e ^ { - s m \\delta } \\delta \\right) \\]",
  "",
  "This reveals that \\( x [ n ] = e ^ { s n \\delta } \\) is an exact eigenfunction of the LSI operator \\( \\mathcal { S } \\). The corresponding eigenvalue is the m-resolution **System Transfer Function** \\( H ( s ) \\in Cl ( 0 , 1 ) \\):",
  "",
  "\\[ H ( s ) = \\sum _ { n = 0 } ^ { N - 1 } h [ n ] e ^ { - s n \\delta } \\delta \\]",
  "",
  "On digital sampled grids \\( \\mathcal { G } _ D \\) with sampling interval \\( \\Delta t \\), substituting the digital bivector variable \\( z = e ^ { s \\Delta t } = r e ^ { \\mathbf { I } \\theta } \\) transforms the system transfer function into the **Digital Transfer Function** \\( H ( z ) \\):",
  "",
  "\\[ H ( z ) = \\sum _ { n = 0 } ^ { N - 1 } h [ n ] z ^ { - n } \\]"
].join("\n");

const chap2Sec3Content = [
  "=== Bilinear Resolution Mapping and System Stability",
  "",
  "To map between m-resolution (analog) system operators \\( s = \\sigma + \\mathbf { I } \\omega \\) and digital sampled operators \\( z = r e ^ { \\mathbf { I } \\theta } \\) without introducing spectrum folding (aliasing) or continuum fallacies, we employ the algebraic **Bilinear Resolution Mapping** (historically known as the Tustin transformation):",
  "",
  "\\[ s = \\frac { 2 } { \\Delta t } \\left( \\frac { 1 - z ^ { - 1 } } { 1 + z ^ { - 1 } } \\right) = \\frac { 2 } { \\Delta t } \\left( \\frac { z - 1 } { z + 1 } \\right) \\]",
  "",
  "The inverse algebraic mapping from m-resolution space to digital phase space is:",
  "\\[ z = \\frac { 1 + \\frac { s \\Delta t } { 2 } } { 1 - \\frac { s \\Delta t } { 2 } } \\]",
  "",
  "==== Phase Warp Distortion and Frequency Precession Map",
  "Evaluating the Bilinear map on the m-resolution stability boundary \\( s = \\mathbf { I } \\Omega \\) and digital boundary \\( z = e ^ { \\mathbf { I } \\theta } \\) yields the exact real bivector relation:",
  "\\[ \\mathbf { I } \\Omega = \\frac { 2 } { \\Delta t } \\left( \\frac { e ^ { \\mathbf { I } \\theta } - 1 } { e ^ { \\mathbf { I } \\theta } + 1 } \\right) = \\mathbf { I } \\frac { 2 } { \\Delta t } \\tan \\left( \\frac { \\theta } { 2 } \\right) \\]",
  "",
  "Equating scalar coefficients yields the non-linear frequency warping equation:",
  "\\[ \\Omega = \\frac { 2 } { \\Delta t } \\tan \\left( \\frac { \\theta } { 2 } \\right) \\implies \\theta = 2 \\arctan \\left( \\frac { \\Omega \\Delta t } { 2 } \\right) \\]",
  "This maps the entire infinite m-resolution frequency range \\( \\Omega \\in ( - \\infty , \\infty ) \\) bijectively onto the finite digital phase interval \\( \\theta \\in ( - \\pi , \\pi ) \\) without frequency overlap.",
  "",
  "==== Bounded-Input Bounded-Output (BIBO) Stability Criteria",
  "An LSI system is BIBO stable if every bounded input sequence \\( \\| x [ n ] \\| \\le M _ x < \\infty \\) produces a bounded output sequence \\( \\| y [ n ] \\| \\le M _ y < \\infty \\).",
  "- **m-Resolution Analog Stability Criterion**: All poles \\( s _ p \\) of \\( H ( s ) \\) must reside strictly in the open left half-plane \\( \\operatorname { Sc } ( s _ p ) = \\sigma _ p < 0 \\).",
  "- **Digital Sampled Stability Criterion**: All poles \\( z _ p \\) of \\( H ( z ) \\) must reside strictly inside the unit bivector circle \\( \\| z _ p \\| = r _ p < 1 \\)."
].join("\n");

const chap2Sec4Content = [
  "=== Rigorous Proofs and System Dynamics Theorems",
  "",
  "[#theorem-lsi-convolution-multiplication-isomorphism]",
  "[THEOREM]",
  ".Theorem: LSI System Convolution-Multiplication Isomorphism Theorem",
  "====",
  "Let \\( x [ n ] \\) and \\( h [ n ] \\) be real-valued digital or analog signals defined on resolution grid \\( \\mathcal { G } _ N \\), and let \\( y [ n ] = ( x * h ) [ n ] \\delta = \\sum _ { m = 0 } ^ { N - 1 } x [ m ] h [ ( n - m ) \\bmod N ] \\delta \\) be their cyclic difference convolution.",
  "",
  "Under the real bivector Discrete Fourier Transform \\( \\mathcal { F } \\), discrete convolution in grid space transforms into exact pointwise multivector multiplication in spectral space:",
  "\\[ \\hat { Y } [ k ] = \\hat { X } [ k ] \\hat { H } [ k ] \\delta \\]",
  "where \\( \\hat { X } [ k ] , \\hat { H } [ k ] \\in Cl ( 0 , 1 ) \\).",
  "",
  "*Proof:*",
  ". **Fourier Expansion of Output Sequence**:",
  "  Apply the real bivector Fourier transform definition to \\( y [ n ] \\):",
  "  \\[ \\hat { Y } [ k ] = \\sum _ { n = 0 } ^ { N - 1 } y [ n ] e ^ { - \\mathbf { I } \\frac { 2 \\pi n k } { N } } \\delta = \\sum _ { n = 0 } ^ { N - 1 } \\left( \\sum _ { m = 0 } ^ { N - 1 } x [ m ] h [ ( n - m ) \\bmod N ] \\delta \\right) e ^ { - \\mathbf { I } \\frac { 2 \\pi n k } { N } } \\delta \\]",
  "",
  ". **Index Substitution and Decoupling**:",
  "  Interchange the order of summation over finite index set \\( \\mathcal { G } _ N \\), and substitute spatial index \\( p = ( n - m ) \\bmod N \\) (so \\( n = p + m \\)):",
  "  \\[ \\hat { Y } [ k ] = \\sum _ { m = 0 } ^ { N - 1 } x [ m ] \\left( \\sum _ { p = 0 } ^ { N - 1 } h [ p ] e ^ { - \\mathbf { I } \\frac { 2 \\pi ( p + m ) k } { N } } \\delta \\right) \\delta \\]",
  "  Using the rotor exponent property \\( e ^ { - \\mathbf { I } \\frac { 2 \\pi ( p + m ) k } { N } } = e ^ { - \\mathbf { I } \\frac { 2 \\pi m k } { N } } e ^ { - \\mathbf { I } \\frac { 2 \\pi p k } { N } } \\):",
  "  \\[ \\hat { Y } [ k ] = \\left( \\sum _ { m = 0 } ^ { N - 1 } x [ m ] e ^ { - \\mathbf { I } \\frac { 2 \\pi m k } { N } } \\delta \\right) \\left( \\sum _ { p = 0 } ^ { N - 1 } h [ p ] e ^ { - \\mathbf { I } \\frac { 2 \\pi p k } { N } } \\delta \\right) = \\hat { X } [ k ] \\hat { H } [ k ] \\delta \\]",
  "  This proves exact isomorphism between discrete convolution and bivector multiplication on \\( \\mathcal { G } _ N \\). \\( \\square \\)",
  "====",
  "",
  "[#theorem-bilinear-bivector-stability-preservation]",
  "[THEOREM]",
  ".Theorem: Bilinear Map Bivector Stability Preservation Theorem",
  "====",
  "The Bilinear transformation \\( z = \\frac { 1 + \\frac { s \\Delta t } { 2 } } { 1 - \\frac { s \\Delta t } { 2 } } \\) maps the open left half-plane of m-resolution Laplace space \\( \\mathcal { H } _ - = \\{ s \\in Cl ( 0 , 1 ) \\mid \\operatorname { Sc } ( s ) = \\sigma < 0 \\} \\) bijectively onto the interior of the digital unit bivector circle \\( \\mathcal { D } _ 1 = \\{ z \\in Cl ( 0 , 1 ) \\mid \\| z \\| < 1 \\} \\).",
  "",
  "*Proof:*",
  ". **Magnitude Evaluation of \\( z \\)**:",
  "  Let \\( s = \\sigma + \\mathbf { I } \\omega \\) with \\( \\sigma < 0 \\). Compute the squared multivector norm \\( \\| z \\| ^ 2 \\):",
  "  \\[ \\| z \\| ^ 2 = \\frac { \\left\\| 1 + \\frac { \\sigma \\Delta t } { 2 } + \\mathbf { I } \\frac { \\omega \\Delta t } { 2 } \\right\\| ^ 2 } { \\left\\| 1 - \\frac { \\sigma \\Delta t } { 2 } - \\mathbf { I } \\frac { \\omega \\Delta t } { 2 } \\right\\| ^ 2 } = \\frac { \\left( 1 + \\frac { \\sigma \\Delta t } { 2 } \\right) ^ 2 + \\left( \\frac { \\omega \\Delta t } { 2 } \\right) ^ 2 } { \\left( 1 - \\frac { \\sigma \\Delta t } { 2 } \\right) ^ 2 + \\left( \\frac { \\omega \\Delta t } { 2 } \\right) ^ 2 } \\]",
  "",
  ". **Algebraic Comparison**:",
  "  Expand the numerator and denominator:",
  "  - Numerator \\( N_z = 1 + \\sigma \\Delta t + \\frac { \\sigma ^ 2 \\Delta t ^ 2 } { 4 } + \\frac { \\omega ^ 2 \\Delta t ^ 2 } { 4 } \\)",
  "  - Denominator \\( D_z = 1 - \\sigma \\Delta t + \\frac { \\sigma ^ 2 \\Delta t ^ 2 } { 4 } + \\frac { \\omega ^ 2 \\Delta t ^ 2 } { 4 } \\)",
  "  Subtracting denominator from numerator yields \\( N_z - D_z = 2 \\sigma \\Delta t \\).",
  "  Since \\( \\sigma < 0 \\) and \\( \\Delta t > 0 \\), \\( N_z - D_z < 0 \\implies N_z < D_z \\). Therefore, \\( \\| z \\| ^ 2 < 1 \\implies \\| z \\| < 1 \\).",
  "  Conversely, if \\( \\sigma = 0 \\), \\( N_z = D_z \\implies \\| z \\| = 1 \\), and if \\( \\sigma > 0 \\), \\( \\| z \\| > 1 \\). This proves exact stability preservation. \\( \\square \\)",
  "===="
].join("\n");

const chap2Sec5Content = [
  "=== Completely Worked Textbook Examples",
  "",
  "==== Example 1: First-Order m-Resolution Analog Filter Impulse Response and Transfer Function",
  "",
  "**Problem Statement:**",
  "Consider a first-order m-resolution physical RC filter defined on grid \\( \\mathcal { G } _ N \\) with lattice spacing \\( \\delta = 0.01 \\text{ s} \\) and cutoff frequency parameter \\( \\alpha = 10 \\text{ s} ^ { - 1 } \\). The physical system difference equation relating input voltage field \\( x [ n ] \\) to output voltage field \\( y [ n ] \\) is:",
  "\\[ \\frac { y [ n ] - y [ n - 1 ] } { \\delta } + \\alpha y [ n ] = \\alpha x [ n ] \\]",
  "1. Derive the discrete unit impulse response sequence \\( h [ n ] \\) for \\( n \\ge 0 \\).",
  "2. Determine the m-resolution transfer function \\( H ( s ) \\) and verify its pole location in bivector Laplace space.",
  "",
  "**Step-by-Step Solution:**",
  "* **Step 1: Impulse Response Derivation**:",
  "  Rearrange the difference equation into recursive state update form:",
  "  \\[ y [ n ] ( 1 + \\alpha \\delta ) = y [ n - 1 ] + \\alpha \\delta x [ n ] \\implies y [ n ] = \\frac { 1 } { 1 + \\alpha \\delta } y [ n - 1 ] + \\frac { \\alpha \\delta } { 1 + \\alpha \\delta } x [ n ] \\]",
  "  Let \\( a = \\frac { 1 } { 1 + \\alpha \\delta } \\). With \\( \\alpha = 10 \\) and \\( \\delta = 0.01 \\):",
  "  \\[ a = \\frac { 1 } { 1 + 10 ( 0.01 ) } = \\frac { 1 } { 1.1 } = \\frac { 10 } { 11 } \\approx 0.90909 \\]",
  "  The input term coefficient is \\( b = \\frac { \\alpha \\delta } { 1 + \\alpha \\delta } = 1 - a = \\frac { 1 } { 11 } \\approx 0.09091 \\).",
  "",
  "  Excite the system with the m-resolution unit impulse \\( x [ n ] = \\delta _ { \\mathcal { G } } [ n ] = \\frac { 1 } { \\delta } \\delta [ n ] = 100 \\delta [ n ] \\) under zero initial conditions \\( y [ - 1 ] = 0 \\):",
  "  - \\( n = 0 \\): \\( y [ 0 ] = a ( 0 ) + b ( 100 ) = \\frac { 1 } { 11 } ( 100 ) = \\frac { 100 } { 11 } \\approx 9.09091 \\)",
  "  - \\( n = 1 \\): \\( y [ 1 ] = a y [ 0 ] = \\left( \\frac { 10 } { 11 } \\right) \\left( \\frac { 100 } { 11 } \\right) = \\frac { 1000 } { 121 } \\approx 8.26446 \\)",
  "  - \\( n = 2 \\): \\( y [ 2 ] = a y [ 1 ] = \\left( \\frac { 10 } { 11 } \\right) ^ 2 \\left( \\frac { 100 } { 11 } \\right) \\approx 7.51315 \\)",
  "  In general, the m-resolution impulse response is:",
  "  \\[ h [ n ] = \\frac { \\alpha } { 1 + \\alpha \\delta } \\left( \\frac { 1 } { 1 + \\alpha \\delta } \\right) ^ n u [ n ] = \\frac { 100 } { 11 } \\left( \\frac { 10 } { 11 } \\right) ^ n u [ n ] \\]",
  "",
  "* **Step 2: Transfer Function Evaluation and Pole Location**:",
  "  Apply the m-resolution Z-transform operator \\( z = e ^ { s \\delta } \\) to the difference equation:",
  "  \\[ \\frac { y [ n ] - y [ n ] z ^ { - 1 } } { \\delta } + \\alpha y [ n ] = \\alpha x [ n ] \\implies Y ( z ) \\left[ \\frac { 1 - z ^ { - 1 } } { \\delta } + \\alpha \\right] = \\alpha X ( z ) \\]",
  "  \\[ H ( z ) = \\frac { Y ( z ) } { X ( z ) } = \\frac { \\alpha } { \\frac { 1 - z ^ { - 1 } } { \\delta } + \\alpha } = \\frac { \\alpha \\delta z } { ( 1 + \\alpha \\delta ) z - 1 } \\]",
  "  The transfer function pole in digital phase space occurs at \\( z _ p = \\frac { 1 } { 1 + \\alpha \\delta } = \\frac { 10 } { 11 } < 1 \\).",
  "  To find the m-resolution pole \\( s _ p = \\sigma _ p + \\mathbf { I } \\omega _ p \\), substitute \\( z _ p = e ^ { s _ p \\delta } \\):",
  "  \\[ e ^ { \\sigma _ p \\delta } = \\frac { 10 } { 11 } \\implies \\sigma _ p = \\frac { 1 } { \\delta } \\ln \\left( \\frac { 10 } { 11 } \\right) = 100 \\ln ( 0.90909 ) \\approx - 9.53102 \\text{ s} ^ { - 1 } \\]",
  "  Since \\( \\sigma _ p = - 9.53102 < 0 \\), the pole lies strictly in the left half-plane of bivector Laplace space, proving that the m-resolution physical filter is BIBO stable.",
  "",
  "==== Example 2: Bilinear Transformation to Digital IIR Filter and Frequency Response",
  "",
  "**Problem Statement:**",
  "An m-resolution analog low-pass filter has the transfer function \\( H_a ( s ) = \\frac { \\Omega _ c } { s + \\Omega _ c } \\) with analog cutoff frequency \\( \\Omega _ c = 100 \\pi \\text{ rad/s} \\).",
  "1. Convert \\( H_a ( s ) \\) into a digital IIR filter transfer function \\( H_d ( z ) \\) using the Bilinear map with digital sampling rate \\( f_s = 1000 \\text{ Hz} \\) (sampling period \\( \\Delta t = 0.001 \\text{ s} \\)).",
  "2. Derive the recursive digital difference equation relating input \\( x [ k ] \\) to output \\( y [ k ] \\).",
  "3. Evaluate the digital filter magnitude response \\( \\| H_d ( e ^ { \\mathbf { I } \\theta } ) \\| \\) at DC (\\( \\theta = 0 \\)) and at the half-Nyquist frequency (\\( \\theta = \\frac { \\pi } { 2 } \\)).",
  "",
  "**Step-by-Step Solution:**",
  "* **Step 1: Applying the Bilinear Map**:",
  "  Substitute \\( s = \\frac { 2 } { \\Delta t } \\frac { 1 - z ^ { - 1 } } { 1 + z ^ { - 1 } } = 2000 \\frac { 1 - z ^ { - 1 } } { 1 + z ^ { - 1 } } \\) into \\( H_a ( s ) \\):",
  "  \\[ H_d ( z ) = \\frac { 100 \\pi } { 2000 \\frac { 1 - z ^ { - 1 } } { 1 + z ^ { - 1 } } + 100 \\pi } = \\frac { 100 \\pi ( 1 + z ^ { - 1 } ) } { 2000 ( 1 - z ^ { - 1 } ) + 100 \\pi ( 1 + z ^ { - 1 } ) } \\]",
  "  Divide numerator and denominator by \\( 100 \\):",
  "  \\[ H_d ( z ) = \\frac { \\pi ( 1 + z ^ { - 1 } ) } { 20 ( 1 - z ^ { - 1 } ) + \\pi ( 1 + z ^ { - 1 } ) } = \\frac { \\pi ( 1 + z ^ { - 1 } ) } { ( 20 + \\pi ) + ( \\pi - 20 ) z ^ { - 1 } } \\]",
  "  With \\( \\pi \\approx 3.14159265 \\):",
  "  - \\( 20 + \\pi \\approx 23.14159265 \\)",
  "  - \\( \\pi - 20 \\approx - 16.85840735 \\)",
  "  Dividing by \\( 20 + \\pi \\):",
  "  \\[ H_d ( z ) = \\frac { 0.13575 ( 1 + z ^ { - 1 } ) } { 1 - 0.72849 z ^ { - 1 } } = \\frac { 0.13575 + 0.13575 z ^ { - 1 } } { 1 - 0.72849 z ^ { - 1 } } \\]",
  "",
  "* **Step 2: Deriving the Recursive Digital Difference Equation**:",
  "  Equating \\( \\frac { Y ( z ) } { X ( z ) } = \\frac { 0.13575 + 0.13575 z ^ { - 1 } } { 1 - 0.72849 z ^ { - 1 } } \\):",
  "  \\[ Y ( z ) ( 1 - 0.72849 z ^ { - 1 } ) = X ( z ) ( 0.13575 + 0.13575 z ^ { - 1 } ) \\]",
  "  Transforming back to digital grid sequence space:",
  "  \\[ y [ k ] - 0.72849 y [ k - 1 ] = 0.13575 x [ k ] + 0.13575 x [ k - 1 ] \\]",
  "  \\[ y [ k ] = 0.72849 y [ k - 1 ] + 0.13575 x [ k ] + 0.13575 x [ k - 1 ] \\]",
  "",
  "* **Step 3: Frequency Response Evaluation**:",
  "  - **DC Frequency (\\( \\theta = 0 \\implies z = 1 \\))**:",
  "    \\[ H_d ( 1 ) = \\frac { 0.13575 ( 1 + 1 ) } { 1 - 0.72849 } = \\frac { 0.27150 } { 0.27151 } \\approx 1.00000 \\]",
  "    The digital filter exhibits exact unit gain at DC.",
  "  - **Half-Nyquist Frequency (\\( \\theta = \\frac { \\pi } { 2 } \\implies z = e ^ { \\mathbf { I } \\pi / 2 } = \\mathbf { I } \\))**:",
  "    \\[ H_d ( \\mathbf { I } ) = \\frac { 0.13575 ( 1 - \\mathbf { I } ) } { 1 + 0.72849 \\mathbf { I } } \\]",
  "    Computing the bivector magnitude:",
  "    \\[ \\| H_d ( \\mathbf { I } ) \\| = \\frac { 0.13575 \\| 1 - \\mathbf { I } \\| } { \\| 1 + 0.72849 \\mathbf { I } \\| } = \\frac { 0.13575 \\sqrt { 1 ^ 2 + ( - 1 ) ^ 2 } } { \\sqrt { 1 ^ 2 + ( 0.72849 ) ^ 2 } } = \\frac { 0.13575 \\sqrt { 2 } } { \\sqrt { 1.53070 } } = \\frac { 0.19198 } { 1.23721 } \\approx 0.15517 \\]",
  "    This demonstrates smooth, non-aliasing high-frequency attenuation executed entirely through real bivector arithmetic."
].join("\n");

const chap3Sec1Content = [
  "=== Thermionic Emission, Child-Langmuir Space Charge Law, and m-Resolution Field Dynamics",
  "",
  "Thermionic vacuum devices operate by regulating the movement of charges liberated from a heated metallic cathode inside an evacuated enclosure. When thermal kinetic excitation overcomes the electrostatic binding work function \\( W_k \\) of the cathode conductor, electrons emerge into the surrounding vacuum gap. On the discrete multiscale resolution grid \\( \\mathcal { G } _ N \\) with spatial step \\( \\delta \\), these liberated charges form a volumetric charge density distribution \\( \\rho [ n ] < 0 \\) in front of the cathode.",
  "",
  "==== Visual and Physical Mechanism of the Space-Charge Barrier",
  "",
  "As electrons enter the vacuum space, their combined negative charge density produces an electrostatic potential minimum—a potential valley—immediately adjacent to the cathode surface. This negative space-charge cloud establishes a self-regulating electrical barrier:",
  "",
  "1. **Potential Valley Formation**: Emitted electrons that leave the cathode with low initial thermal velocities are repelled by the negative potential valley and return to the cathode surface.",
  "2. **Anode Field Penetration**: When a positive potential \\( V_p > 0 \\) is applied to the anode (plate), the resulting electrostatic field penetrates the vacuum gap, lifting the potential profile across \\( \\mathcal { G } _ N \\) and lowering the potential valley barrier.",
  "3. **Equilibrium Flux**: Only electrons possessing sufficient kinetic energy to cross the potential minimum are accelerated across the inter-electrode gap toward the anode, establishing a stable, space-charge limited current.",
  "",
  "==== Derivation of the Child-Langmuir 3/2-Power Law on Grid \\( \\mathcal { G } _ N \\)",
  "",
  "Consider a planar vacuum diode with cathode situated at grid position \\( n = 0 \\) (at potential \\( \\Phi [ 0 ] = 0 \\)) and anode at grid position \\( n = N_d \\) corresponding to gap distance \\( d = N_d \\delta \\) (at potential \\( \\Phi [ N_d ] = V_p \\)). The discrete electrostatic potential \\( \\Phi [ n ] \\) satisfies the discrete 1D Poisson equation on \\( \\mathcal { G } _ N \\):",
  "",
  "\\[ \\Delta _ { \\delta } \\Phi [ n ] = \\frac { \\Phi [ n + 1 ] - 2 \\Phi [ n ] + \\Phi [ n - 1 ] } { \\delta ^ 2 } = - \\frac { \\rho [ n ] } { \\epsilon _ 0 } \\]",
  "",
  "An electron accelerated from potential minimum \\( \\Phi = 0 \\) to grid position \\( n \\) converts electrostatic energy into kinetic energy over finite duration \\( \\tau \\):",
  "",
  "\\[ \\frac { 1 } { 2 } m _ e v [ n ] ^ 2 = q \\Phi [ n ] \\implies v [ n ] = \\sqrt { \\frac { 2 q \\Phi [ n ] } { m _ e } } \\]",
  "",
  "Under steady space-charge limited flow, current continuity requires a constant charge flux density \\( J = - \\rho [ n ] v [ n ] \\). Expressing charge density as \\( \\rho [ n ] = - J \\sqrt { \\frac { m _ e } { 2 q \\Phi [ n ] } } \\) and passing to the fine resolution limit on \\( \\mathcal { G } _ N \\) yields:",
  "",
  "\\[ \\frac { \\mathrm { d } ^ 2 \\Phi } { \\mathrm { d } z ^ 2 } = \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\Phi ^ { - 1 / 2 } \\]",
  "",
  "Multiplying both sides by \\( 2 \\frac { \\mathrm { d } \\Phi } { \\mathrm { d } z } \\) and integrating with respect to \\( z \\) with boundary conditions \\( \\Phi ( 0 ) = 0 \\) and \\( \\left. \\frac { \\mathrm { d } \\Phi } { \\mathrm { d } z } \\right| _ { 0 } = 0 \\):",
  "",
  "\\[ \\left( \\frac { \\mathrm { d } \\Phi } { \\mathrm { d } z } \\right) ^ 2 = \\frac { 4 J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\Phi ^ { 1 / 2 } \\implies \\frac { \\mathrm { d } \\Phi } { \\mathrm { d } z } = 2 \\left( \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\right) ^ { 1 / 2 } \\Phi ^ { 1 / 4 } \\]",
  "",
  "Separating variables and integrating from \\( z = 0 \\) to \\( z = d \\) (where \\( \\Phi ( d ) = V_p \\)):",
  "",
  "\\[ \\int _ 0 ^ { V_p } \\Phi ^ { - 1 / 4 } \\mathrm { d } \\Phi = 2 \\left( \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\right) ^ { 1 / 2 } \\int _ 0 ^ d \\mathrm { d } z \\]",
  "",
  "\\[ \\frac { 4 } { 3 } V_p ^ { 3 / 4 } = 2 d \\left( \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\right) ^ { 1 / 2 } \\]",
  "",
  "Squaring both sides and solving for current density \\( J \\) yields the exact **Child-Langmuir 3/2-Power Law**:",
  "",
  "\\[ J = \\frac { 4 \\epsilon _ 0 } { 9 } \\sqrt { \\frac { 2 q } { m _ e } } \\frac { V_p ^ { 3 / 2 } } { d ^ 2 } \\]",
  "",
  "==== Triode Parameters and Small-Signal Linearization",
  "",
  "Inserting a wire mesh control grid close to the cathode at distance \\( d _ { cg } \\ll d \\) modifies the effective electrostatic potential driving cathode emission:",
  "",
  "\\[ V _ { eff } = V_g + \\frac { V_p } { \\mu } \\]",
  "",
  "where \\( \\mu \\) is the electrostatic amplification factor determined by the geometric grid wire pitch and spacing. The plate current follows:",
  "",
  "\\[ I_p = K \\left( V_g + \\frac { V_p } { \\mu } \\right) ^ { 3 / 2 } \\]",
  "",
  "Small-signal linear variations around a stable operating point \\( ( V_g , V_p , I_p ) \\) are governed by three fundamental parameters:",
  "",
  "1. **Transconductance \\( g_m \\)**: \\( g_m = \\left. \\frac { \\partial I_p } { \\partial V_g } \\right| _ { V_p } = \\frac { 3 } { 2 } K \\left( V_g + \\frac { V_p } { \\mu } \\right) ^ { 1 / 2 } \\)",
  "2. **Dynamic Plate Resistance \\( r_p \\)**: \\( r_p = \\left( \\left. \\frac { \\partial I_p } { \\partial V_p } \\right| _ { V_g } \\right) ^ { - 1 } = \\frac { \\mu } { g_m } \\)",
  "3. **Amplification Factor \\( \\mu \\)**: \\( \\mu = g_m \\cdot r_p \\) (the Barkhausen Triode Relation)."
].join("\n");

const chap3Sec2Content = [
  "=== Multi-Electrode Thermionic Valves: Diodes, Triodes, Tetrodes, Pentodes, Beam Power Tubes, and Multigrid Mixers",
  "",
  "The evolution of thermionic devices from simple rectifiers to complex signal processors reflects the progressive introduction of specialized electrostatic control grids.",
  "",
  "==== Thermionic Diodes and Triodes",
  "",
  "* **Vacuum Diodes**: Comprise a heated cathode and an anode. Used exclusively as unidirectional high-voltage rectifiers and envelope detectors. Below space-charge saturation, current follows the Child-Langmuir 3/2 law; at extremely high temperatures, current saturates at the Richardson emission limit.",
  "* **Vacuum Triodes**: Introduce a control grid mesh between cathode and plate. While offering high voltage amplification, triodes suffer from significant inter-electrode capacitance \\( C _ { gp } \\) between grid and plate. Under high voltage gain \\( A_v \\), the **Miller Effect** multiplies the effective input capacitance to \\( C _ { in } = C _ { gk } + C _ { gp } ( 1 + | A_v | ) \\), severely restricting high-frequency bandwidth.",
  "",
  "==== The Tetrode and Secondary Emission Dynamics",
  "",
  "To eliminate high inter-electrode capacitance \\( C _ { gp } \\), the **Tetrode** inserts a second grid—the **Screen Grid** (held at a fixed positive DC potential \\( V _ { g2 } \\))—between control grid and anode. The screen grid acts as an electrostatic shield, reducing \\( C _ { gp } \\) by more than two orders of magnitude.",
  "",
  "However, primary electrons accelerated toward the anode arrive with substantial kinetic energy, knocking loose **secondary electrons** from the metallic anode surface. When the anode potential drops below the screen potential (\\( V_p < V _ { g2 } \\)), the positive screen grid attracts these secondary electrons away from the anode. This produces a negative differential resistance region—the **tetrode dynatron kink**—where increasing plate voltage causes plate current to fall, inducing parametric instability in power amplifiers.",
  "",
  "==== The Pentode and Suppressor Grid Action",
  "",
  "The **Pentode** overcomes secondary emission by introducing a third grid—the **Suppressor Grid**—located between screen grid and anode. Connected directly to the cathode (zero potential), the suppressor grid establishes an electrostatic potential barrier in front of the anode:",
  "",
  "1. High-velocity primary electrons from the cathode easily pass through the coarse suppressor mesh to strike the anode.",
  "2. Low-velocity secondary electrons knocked loose from the anode face a repulsive electrostatic potential hill created by the zero-volt suppressor grid.",
  "3. Secondary electrons are turned back and re-collected by the anode, eliminating the dynatron kink and producing smooth, monotonic plate characteristic curves with exceptionally high dynamic plate resistance \\( r_p \\).",
  "",
  "==== Beam Power Tubes and Virtual Cathode Space-Charge Suppression",
  "",
  "Rather than using a physical suppressor wire mesh—which intercepts electrons and wastes screen current—the **Beam Power Tube** uses specialized beam-forming deflector plates combined with aligned control and screen grid wires.",
  "",
  "The deflector plates compress the electron stream into dense, highly concentrated electron sheets. In the space between screen grid and anode, the concentrated negative charge density of the electron beam produces its own deep potential minimum—a **virtual cathode**—at low plate voltages. This virtual cathode repels secondary electrons back into the anode without physical grid wires, yielding lower screen current dissipation, higher power conversion efficiency, and significantly lower third-harmonic distortion in power output stages.",
  "",
  "==== Multigrid Frequency Converters and Mixers",
  "",
  "For superheterodyne radio reception, specialized multigrid valves incorporate up to five grids (**Hexodes, Heptodes, Octodes, and Pentagrid Mixers**). Two independent control grids—Grid 1 (RF signal \\( v _ { RF } \\)) and Grid 3 (Local Oscillator \\( v _ { LO } \\))—are separated and shielded by screen grids (Grids 2 and 4).",
  "",
  "The resulting plate current is directly proportional to the multiplicative product of both control signals:",
  "",
  "\\[ I_p ( t ) = g_c \\, v _ { RF } ( t ) \\, v _ { LO } ( t ) \\]",
  "",
  "By trigonometric bivector decomposition, \\( \\cos ( \\omega _ { RF } t ) \\cos ( \\omega _ { LO } t ) = \\frac { 1 } { 2 } [ \\cos ( ( \\omega _ { RF } - \\omega _ { LO } ) t ) + \\cos ( ( \\omega _ { RF } + \\omega _ { LO } ) t ) ] \\). This multiplicative mixing executes frequency translation to a fixed Intermediate Frequency (IF) with complete isolation between input signal channels."
].join("\n");

const chap3Sec3Content = [
  "=== Cathode-Ray Tubes and Specialized Vacuum Devices: Electrostatic, Electromagnetic, Storage, and Image Tubes",
  "",
  "Cathode-Ray Tubes (CRTs) and specialized beam devices manipulate accelerated electron beams to display visual information, store electrical charges, or generate microwave signals.",
  "",
  "==== Electron Gun Optics and Focusing Mechanisms",
  "",
  "An electron gun generates, accelerates, and focuses a narrow electron beam toward a display screen or target anode:",
  "",
  "1. **Thermionic Cathode and Wehnelt Cylinder**: A heated cathode emits electrons inside a cylindrical control grid (Wehnelt cylinder) held at negative bias. Varying the grid bias modulates electron beam intensity (brightness z-axis modulation).",
  "2. **Electrostatic Immersion Lenses**: Consecutive cylindrical anodes held at ascending positive potentials (\\( V_1 < V_2 < V_a \\)) create curved electrostatic equipotential surfaces. The electrostatic force field bends electron trajectories toward the central longitudinal axis, focusing the beam to a fine spot.",
  "3. **Magnetic Lens Focusing**: An axial solenoid coil generates a longitudinal magnetic field \\( \\mathbf { B } = B_z e_3 \\). Electrons possessing radial velocity components \\( v_r \\) experience a transverse Lorentz force \\( \\mathbf { F } = q ( \\mathbf { v } \\times \\mathbf { B } ) \\), driving them into helical trajectories. The cyclotron precession frequency \\( \\omega_c = \\frac { q B_z } { m_e } \\) forces all diverging electrons to complete a full revolution during transit period \\( \\tau_c = \\frac { 2 \\pi m_e } { q B_z } \\), converging to a sharp focal point on the screen.",
  "",
  "==== Deflection Dynamics: Electrostatic vs. Electromagnetic Steering",
  "",
  "* **Electrostatic Deflection**: Uses parallel deflection plates of length \\( l \\), separation \\( d \\), with applied deflection voltage \\( V_d \\). Electrons with axial velocity \\( v_z = \\sqrt { \\frac { 2 q V_a } { m_e } } \\) experience transverse acceleration \\( a_y = \\frac { q V_d } { m_e d } \\) over transit time \\( \\tau = \\frac { l } { v_z } \\). On a screen at distance \\( L \\), total beam spot displacement is:",
  "  \\[ y = \\frac { L \\, l \\, V_d } { 2 \\, d \\, V_a } \\]",
  "  The electrostatic deflection sensitivity \\( S_e = \\frac { y } { V_d } = \\frac { L \\, l } { 2 \\, d \\, V_a } \\) is inversely proportional to acceleration potential \\( V_a \\). Electrostatic deflection is preferred for high-speed laboratory oscilloscopes due to its high input impedance and fast signal response.",
  "",
  "* **Electromagnetic Deflection**: Uses external magnetic deflection yokes generating a transverse magnetic field \\( B_x \\). The transverse Lorentz force curves the electron trajectory into a circular arc of radius \\( R = \\frac { m_e v_z } { q B_x } \\). On a screen at distance \\( L \\), the spot deflection is:",
  "  \\[ y \\approx \\frac { q \\, L \\, l \\, B_x } { \\sqrt { 2 \\, q \\, m_e \\, V_a } } \\]",
  "  Because magnetic deflection sensitivity \\( S_m \\propto \\frac { 1 } { \\sqrt { V_a } } \\) decreases much slower with acceleration voltage than electrostatic sensitivity, electromagnetic deflection allows very high acceleration potentials (yielding intense screen brightness) and wide deflection angles (up to \\( 110 ^ \\circ \\)) in television CRTs and radar display monitors.",
  "",
  "==== Specialized Cathode-Ray Tubes",
  "",
  "1. **Direct-View Storage Tubes (DVST)**:",
  "   Incorporate two distinct electron guns: a high-resolution focused **Writing Gun** and a wide-angle **Flood Gun**. The writing gun deposits a high-density positive charge pattern onto a fine dielectric storage mesh via secondary electron emission ratio \\( \\delta > 1 \\). Low-velocity flood gun electrons pass through positively charged mesh apertures to strike the phosphor screen while being repelled by uncharged negative mesh apertures, displaying bright, flicker-free traces for hours without requiring electronic digital refresh memory.",
  "",
  "2. **Post-Deflection Acceleration (PDA) and Traveling-Wave CRTs**:",
  "   High-frequency analog oscilloscopes maintain low accelerating voltage in the deflection plate region to maximize deflection sensitivity, followed by a high-resistance spiral anode band (PDA) that post-accelerates electrons to high impact velocity at the screen. For gigahertz-bandwidth transients, **traveling-wave deflection structures** replace solid plates with helical or meander-line delay lines whose electrical signal phase velocity matches electron beam velocity (\\( v_p = v_z \\)), eliminating transit-time signal blurring.",
  "",
  "3. **Image Pick-up Tubes (Image Orthicon and Vidicon)**:",
  "   Convert optical images into video signals. The **Vidicon** uses a photoconductive target layer whose localized electrical resistance drops proportionally to incident light intensity; a scanning electron beam recharges the target, generating an output current signal across a load resistor. The **Image Orthicon** combines a photoemissive photocathode, target mesh storage, and an internal multi-stage secondary electron multiplier surrounding the electron gun, enabling high-sensitivity television camera capture in low-light environments.",
  "",
  "==== Microwave Vacuum Devices: Klystrons and Magnetrons",
  "",
  "* **Klystrons**: Utilize **velocity modulation**. An input RF signal across a resonant cavity gap accelerates or decelerates electrons passing through. In a downstream drift tube, faster electrons overtake slower electrons, producing dense electron bunches (**density modulation**). The bunched beam excites high-power microwave oscillations in an output resonant cavity.",
  "* **Magnetrons**: High-power crossed-field microwave generators (\\( \\mathbf { E } \\perp \\mathbf { B } \\)). A central cylindrical cathode surrounded by an anode block containing resonant cavity vanes creates radial electric fields and axial magnetic fields. Electrons execute cycloidal drift orbits, forming rotating space-charge spokes that transfer kinetic energy to the resonant microwave fields of the anode cavities with efficiency exceeding 70%."
].join("\n");

const chap3Sec4Content = [
  "=== Formal Postulates and Theorems of Vacuum Tube Field Dynamics",
  "",
  "[#postulate-space-charge-minimum]",
  "[POSTULATE]",
  ".Postulate: Thermionic Space Charge Potential Minimum",
  "In any evacuated inter-electrode gap bounded by a heated thermionic cathode at potential \\( \\Phi_k = 0 \\) and an anode at potential \\( V_p > 0 \\), the equilibrium space-charge distribution \\( \\rho [ n ] \\le 0 \\) on resolution grid \\( \\mathcal { G } _ N \\) produces a strictly non-positive potential minimum \\( \\Phi _ { min } \\le 0 \\) situated in the immediate spatial vicinity of the cathode surface, regulating electron flow into the acceleration field.",
  "",
  "[#theorem-child-langmuir-law]",
  "[THEOREM]",
  ".Theorem: Child-Langmuir 3/2-Power Space Charge Law on Grid \\( \\mathcal { G } _ N \\)",
  "Under space-charge limited operation across an evacuated planar gap of width \\( d \\) on resolution grid \\( \\mathcal { G } _ N \\), the current density \\( J \\) drawn by anode potential \\( V_p \\) satisfies:",
  "\\[ J = \\frac { 4 \\epsilon _ 0 } { 9 } \\sqrt { \\frac { 2 q } { m _ e } } \\frac { V_p ^ { 3 / 2 } } { d ^ 2 } \\]",
  "",
  "*Proof*:",
  "Let \\( \\Phi [ n ] \\) be the electrostatic potential on \\( \\mathcal { G } _ N \\). Energy conservation for an electron accelerated from potential minimum \\( \\Phi = 0 \\) gives velocity \\( v [ n ] = \\sqrt { \\frac { 2 q \\Phi [ n ] } { m _ e } } \\). Current continuity requires constant charge flux \\( J = - \\rho [ n ] v [ n ] \\). Substituting \\( \\rho [ n ] = - J \\sqrt { \\frac { m _ e } { 2 q \\Phi [ n ] } } \\) into the discrete Poisson equation \\( \\Delta _ { \\delta } \\Phi [ n ] = - \\frac { \\rho [ n ] } { \\epsilon _ 0 } \\) yields in the fine grid limit:",
  "\\[ \\frac { \\mathrm { d } ^ 2 \\Phi } { \\mathrm { d } z ^ 2 } = \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\Phi ^ { - 1 / 2 } \\]",
  "Multiplying both sides by \\( 2 \\frac { \\mathrm { d } \\Phi } { \\mathrm { d } z } \\) and integrating with respect to \\( z \\) using boundary conditions \\( \\Phi ( 0 ) = 0 \\) and \\( \\left. \\frac { \\mathrm { d } \\Phi } { \\mathrm { d } z } \\right| _ { 0 } = 0 \\):",
  "\\[ \\left( \\frac { \\mathrm { d } \\Phi } { \\mathrm { d } z } \\right) ^ 2 = \\frac { 4 J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\Phi ^ { 1 / 2 } \\implies \\frac { \\mathrm { d } \\Phi } { \\mathrm { d } z } = 2 \\left( \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\right) ^ { 1 / 2 } \\Phi ^ { 1 / 4 } \\]",
  "Separating variables and integrating from \\( z = 0 \\) to \\( z = d \\):",
  "\\[ \\int _ 0 ^ { V_p } \\Phi ^ { - 1 / 4 } \\mathrm { d } \\Phi = 2 \\left( \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\right) ^ { 1 / 2 } \\int _ 0 ^ d \\mathrm { d } z \\]",
  "\\[ \\frac { 4 } { 3 } V_p ^ { 3 / 4 } = 2 d \\left( \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\right) ^ { 1 / 2 } \\]",
  "Squaring both sides:",
  "\\[ \\frac { 16 } { 9 } V_p ^ { 3 / 2 } = 4 d ^ 2 \\frac { J } { \\epsilon _ 0 } \\sqrt { \\frac { m _ e } { 2 q } } \\implies J = \\frac { 4 \\epsilon _ 0 } { 9 } \\sqrt { \\frac { 2 q } { m _ e } } \\frac { V_p ^ { 3 / 2 } } { d ^ 2 } \\]",
  "This completes the formal proof. \\(\\blacksquare\\)",
  "",
  "[#theorem-barkhausen-relation]",
  "[THEOREM]",
  ".Theorem: Barkhausen Triode Parameter Relation Theorem",
  "For any triode tube operating in its linear small-signal region, the amplification factor \\( \\mu \\), transconductance \\( g_m \\), and dynamic plate resistance \\( r_p \\) satisfy the exact identity:",
  "\\[ \\mu = g_m \\cdot r_p \\]",
  "",
  "*Proof*:",
  "The total differential of plate current \\( I_p = f ( V_g , V_p ) \\) is given by:",
  "\\[ \\mathrm { d } I_p = \\left. \\frac { \\partial I_p } { \\partial V_g } \\right| _ { V_p } \\mathrm { d } V_g + \\left. \\frac { \\partial I_p } { \\partial V_p } \\right| _ { V_g } \\mathrm { d } V_p \\]",
  "By definition, \\( g_m = \\left. \\frac { \\partial I_p } { \\partial V_g } \\right| _ { V_p } \\) and \\( \\frac { 1 } { r_p } = \\left. \\frac { \\partial I_p } { \\partial V_p } \\right| _ { V_g } \\). Holding plate current constant (\\( \\mathrm { d } I_p = 0 \\)):",
  "\\[ 0 = g_m \\mathrm { d } V_g + \\frac { 1 } { r_p } \\mathrm { d } V_p \\implies \\left. - \\frac { \\mathrm { d } V_p } { \\mathrm { d } V_g } \\right| _ { I_p } = g_m \\cdot r_p \\]",
  "Since the amplification factor is defined as \\( \\mu = \\left. - \\frac { \\mathrm { d } V_p } { \\mathrm { d } V_g } \\right| _ { I_p } \\), we obtain \\( \\mu = g_m \\cdot r_p \\). \\(\\blacksquare\\)",
  "",
  "[#theorem-crt-deflection-sensitivity]",
  "[THEOREM]",
  ".Theorem: Electrostatic CRT Deflection Sensitivity Theorem",
  "For an electrostatic CRT with acceleration voltage \\( V_a \\), deflection plate length \\( l \\), plate separation \\( d \\), and plate-to-screen distance \\( L \\), the deflection sensitivity \\( S_e = \\frac { y } { V_d } \\) is inversely proportional to acceleration voltage \\( V_a \\):",
  "\\[ S_e = \\frac { L \\, l } { 2 \\, d \\, V_a } \\]",
  "",
  "*Proof*:",
  "Electron axial velocity is \\( v_z = \\sqrt { \\frac { 2 q V_a } { m _ e } } \\). Transit duration through deflection plates is \\( \\tau = \\frac { l } { v_z } \\). The uniform electric field between plates is \\( E_y = \\frac { V_d } { d } \\), producing transverse acceleration \\( a_y = \\frac { q V_d } { m _ e d } \\). Exit transverse velocity is \\( v_y = a_y \\tau = \\frac { q V_d l } { m _ e d v_z } \\). The exit deflection angle \\( \\theta \\) satisfies \\( \\tan \\theta = \\frac { v_y } { v_z } = \\frac { q V_d l } { m _ e d v_z ^ 2 } = \\frac { q V_d l } { m _ e d ( 2 q V_a / m _ e ) } = \\frac { V_d l } { 2 d V_a } \\). On a screen at distance \\( L \\), total beam displacement is \\( y = L \\tan \\theta = \\frac { L l V_d } { 2 d V_a } \\). Dividing by \\( V_d \\) yields \\( S_e = \\frac { L l } { 2 d V_a } \\). \\(\\blacksquare\\)"
].join("\n");

const chap3Sec5Content = [
  "=== Completely Worked Technical Examples",
  "",
  "==== Example 1: Triode Small-Signal Amplifier Analysis with Miller Effect",
  "",
  "**Problem Statement:**",
  "A triode vacuum tube operates with amplification factor \\( \\mu = 50 \\), dynamic plate resistance \\( r_p = 10 \\text{ k} \\Omega \\), load resistance \\( R_L = 40 \\text{ k} \\Omega \\), grid-to-cathode capacitance \\( C _ { gk } = 3.0 \\text{ pF} \\), and grid-to-plate capacitance \\( C _ { gp } = 2.5 \\text{ pF} \\).",
  "1. Calculate the triode transconductance \\( g_m \\).",
  "2. Calculate the small-signal voltage gain \\( A_v \\) of the amplifier stage.",
  "3. Determine the total effective input capacitance \\( C _ { in } \\) seen by the signal source driving the grid.",
  "",
  "**Step-by-Step Solution:**",
  "* **Step 1: Calculating Transconductance \\( g_m \\)**:",
  "  By the Barkhausen relation theorem, \\( g_m = \\frac { \\mu } { r_p } \\):",
  "  \\[ g_m = \\frac { 50 } { 10000 \\text{ } \\Omega } = 0.0050 \\text{ S} = 5.0 \\text{ mA/V} \\]",
  "",
  "* **Step 2: Calculating Small-Signal Voltage Gain \\( A_v \\)**:",
  "  The small-signal equivalent circuit yields voltage gain:",
  "  \\[ A_v = - \\frac { \\mu R_L } { r_p + R_L } = - \\frac { 50 \\times 40000 } { 10000 + 40000 } = - \\frac { 2000000 } { 50000 } = - 40.0 \\]",
  "",
  "* **Step 3: Calculating Miller Input Capacitance \\( C _ { in } \\)**:",
  "  Applying the Miller Effect transformation:",
  "  \\[ C _ { in } = C _ { gk } + C _ { gp } ( 1 + | A_v | ) = 3.0 \\text{ pF} + 2.5 \\text{ pF} \\times ( 1 + 40.0 ) = 3.0 + 2.5 \\times 41.0 = 3.0 + 102.5 = 105.5 \\text{ pF} \\]",
  "  The Miller multiplication increases effective input capacitance by over a factor of 20.",
  "",
  "==== Example 2: High-Bandwidth Electrostatic Cathode-Ray Tube Analysis",
  "",
  "**Problem Statement:**",
  "An electrostatic CRT operates with acceleration voltage \\( V_a = 2000 \\text{ V} \\), deflection plate length \\( l = 0.03 \\text{ m} \\), plate separation \\( d = 0.005 \\text{ m} \\), and screen distance \\( L = 0.25 \\text{ m} \\). (Given: \\( q / m_e = 1.7588 \\times 10 ^ { 11 } \\text{ C/kg} \\)).",
  "1. Calculate electron axial velocity \\( v_z \\).",
  "2. Calculate electron transit duration \\( \\tau \\) through the deflection plates.",
  "3. Calculate deflection sensitivity \\( S_e \\) in mm/V.",
  "4. Determine the upper 3 dB bandwidth limit \\( f _ { max } \\) imposed by transit-time signal degradation where \\( \\omega \\tau = \\pi \\).",
  "",
  "**Step-by-Step Solution:**",
  "* **Step 1: Axial Velocity \\( v_z \\)**:",
  "  \\[ v_z = \\sqrt { 2 \\left( \\frac { q } { m_e } \\right) V_a } = \\sqrt { 2 \\times 1.7588 \\times 10 ^ { 11 } \\times 2000 } = \\sqrt { 7.0352 \\times 10 ^ { 14 } } \\approx 2.6524 \\times 10 ^ 7 \\text{ m/s} \\]",
  "",
  "* **Step 2: Transit Duration \\( \\tau \\)**:",
  "  \\[ \\tau = \\frac { l } { v_z } = \\frac { 0.03 \\text{ m} } { 2.6524 \\times 10 ^ 7 \\text{ m/s} } \\approx 1.1310 \\times 10 ^ { - 9 } \\text{ s} = 1.131 \\text{ ns} \\]",
  "",
  "* **Step 3: Deflection Sensitivity \\( S_e \\)**:",
  "  \\[ S_e = \\frac { L \\, l } { 2 \\, d \\, V_a } = \\frac { 0.25 \\times 0.03 } { 2 \\times 0.005 \\times 2000 } = \\frac { 0.0075 } { 20 } = 0.000375 \\text{ m/V} = 0.375 \\text{ mm/V} \\]",
  "",
  "* **Step 4: Bandwidth Limit \\( f _ { max } \\)**:",
  "  \\[ \\omega _ { max } \\tau = \\pi \\implies f _ { max } = \\frac { 1 } { 2 \\tau } = \\frac { 1 } { 2 \\times 1.1310 \\times 10 ^ { - 9 } \\text{ s} } \\approx 4.421 \\times 10 ^ 8 \\text{ Hz} = 442.1 \\text{ MHz} \\]",
  "",
  "==== Example 3: Beam Power Tube Virtual Cathode Suppression and Efficiency",
  "",
  "**Problem Statement:**",
  "A beam power tube operates at plate potential \\( V_p = 250 \\text{ V} \\) and screen grid potential \\( V _ { g2 } = 250 \\text{ V} \\). Space-charge concentration creates a virtual cathode potential dip \\( \\Delta V = 60 \\text{ V} \\) between screen and plate. Total cathode emission current is \\( I_k = 100 \\text{ mA} \\).",
  "1. Determine the minimum potential \\( V _ { min } \\) between screen grid and plate.",
  "2. Explain why secondary electrons emitted from the anode (energies \\( 5 - 15 \\text{ eV} \\)) are fully repelled.",
  "3. Compare screen grid power loss between the beam power tube (5% screen current) and an unsuppressed tetrode (25% screen current).",
  "",
  "**Step-by-Step Solution:**",
  "* **Step 1: Minimum Potential \\( V _ { min } \\)**:",
  "  \\[ V _ { min } = V_p - \\Delta V = 250 \\text{ V} - 60 \\text{ V} = 190 \\text{ V} \\]",
  "* **Step 2: Secondary Electron Repulsion Mechanism**:",
  "  Secondary electrons emitted from the anode face an electrostatic potential hill rising from \\( V_p = 250 \\text{ V} \\) down to \\( V _ { min } = 190 \\text{ V} \\) (a potential hill of \\( 60 \\text{ V} \\)). Since secondary electron initial kinetic energies (\\( \\le 15 \\text{ eV} \\)) are far lower than the 60 eV potential barrier, 100% of secondary electrons are repelled back into the anode.",
  "* **Step 3: Screen Power Dissipation Comparison**:",
  "  - **Tetrode**: Screen current \\( I _ { g2 } = 0.25 \\times 100 \\text{ mA} = 25 \\text{ mA} \\). Screen power dissipation \\( P _ { g2 } = 0.025 \\text{ A} \\times 250 \\text{ V} = 6.25 \\text{ W} \\). Useful plate current \\( I_p = 75 \\text{ mA} \\).",
  "  - **Beam Power Tube**: Screen current \\( I _ { g2 } = 0.05 \\times 100 \\text{ mA} = 5 \\text{ mA} \\). Screen power dissipation \\( P _ { g2 } = 0.005 \\text{ A} \\times 250 \\text{ V} = 1.25 \\text{ W} \\). Useful plate current \\( I_p = 95 \\text{ mA} \\).",
  "  The beam power tube saves 5.0 W of wasted screen heat while delivering 26.7% higher plate current to the output load."
].join("\n");

const volume5Object = {
  id: "volume-5-spectral-electronics-computing",
  title: "The Iris Number System",
  subtitle: "Volume V: Spectral Analysis, Electronics, Computing",
  author: "Frédéric Blondin Custer",
  version: "1.0.0",
  lastUpdated: "2026-08-08",
  description: "Volume V establishes first-principles spectral analysis, electronics, and digital computing on discrete multiscale resolution grids without complex numbers, complex planes, or continuum infinities, unifying Fourier, Cosine, Sine, Hartley, Laplace, Z, Mellin, Hankel, Radon, and Wavelet transforms within real geometric bivector phase space.",
  filename: "Iris_Number_System-05-Volume_V_Spectral_Analysis_etc.adoc",
  chapters: [
    {
      id: "chap-unified-spectral-analysis",
      title: "First-Principles Unified Spectral Analysis without Complex Numbers",
      summary: "This chapter establishes a unified mathematical framework for all major linear spectral transforms on discrete multiscale resolution grids \\( \\mathcal { G } _ N \\), demonstrating that complex numbers and continuum planes are unnecessary contrivances when signals and operators are represented via real geometric bivectors and linear difference matrices.",
      sections: [
        {
          id: "sec-fallacy-complex-plane-real-bivector-kinematics",
          title: "The Fallacy of the Continuum Complex Plane and Real Bivector Kinematics",
          contentAsciiDoc: sec1Content
        },
        {
          id: "sec-unified-operator-kernel-formulation",
          title: "Unified Operator Kernel Formulation for Conventional Transforms",
          contentAsciiDoc: sec2Content
        },
        {
          id: "sec-rigorous-proofs-spectral-theorems",
          title: "Rigorous Proofs and Mathematical Theorems",
          contentAsciiDoc: sec3Content
        },
        {
          id: "sec-completely-worked-textbook-examples",
          title: "Completely Worked Textbook Examples",
          contentAsciiDoc: sec4Content
        }
      ]
    },
    {
      id: "chap-impulse-responses-transfer-functions",
      title: "Theory of Impulse Responses and Transfer Functions: m-Resolution Analog and Digital System Dynamics",
      summary: "This chapter formulates the linear theory of physical systems, impulse responses, difference convolution operators, and transfer functions across m-resolution (analog) physical grids and digital sampled grids without continuum infinities or point-mass idealizations.",
      sections: [
        {
          id: "sec-m-res-and-digital-system-paradigms",
          title: "m-Resolution Analog and Digital System Paradigms",
          contentAsciiDoc: chap2Sec1Content
        },
        {
          id: "sec-shift-invariant-convolution-transfer-functions",
          title: "Shift-Invariant Systems, Difference Convolution, and Bivector Transfer Functions",
          contentAsciiDoc: chap2Sec2Content
        },
        {
          id: "sec-bilinear-resolution-mapping-stability",
          title: "Bilinear Resolution Mapping and System Stability",
          contentAsciiDoc: chap2Sec3Content
        },
        {
          id: "sec-proofs-system-dynamics-theorems",
          title: "Rigorous Proofs and System Dynamics Theorems",
          contentAsciiDoc: chap2Sec4Content
        },
        {
          id: "sec-worked-examples-impulse-transfer",
          title: "Completely Worked Textbook Examples",
          contentAsciiDoc: chap2Sec5Content
        }
      ]
    },
    {
      id: "chap-electron-tubes-thermionic-valves",
      title: "Theory of Electron Tubes and Thermionic Valves: Field Physics, Grid Control, and Specialized Cathode-Ray Devices",
      summary: "This chapter develops the physical theory of thermionic emission, space charge dynamics, grid voltage modulation, and multi-electrode electron tubes (valves) within the m-resolution framework of the Master Field Equation. In addition to fundamental diodes, triodes, tetrodes, and pentodes, detailed analyses are given for specialized devices including beam power tubes, heptodes/hexodes, klystrons, magnetrons, and diverse cathode-ray tubes (electrostatic and electromagnetic display CRTs, storage tubes, traveling-wave oscilloscopes, and image orthicons/vidicons).",
      sections: [
        {
          id: "sec-thermionic-emission-space-charge-dynamics",
          title: "Thermionic Emission, Child-Langmuir Space Charge Law, and m-Resolution Field Dynamics",
          contentAsciiDoc: chap3Sec1Content
        },
        {
          id: "sec-multi-electrode-valves",
          title: "Multi-Electrode Valves: Diodes, Triodes, Tetrodes, Pentodes, Beam Power Tubes, and Multigrid Mixers",
          contentAsciiDoc: chap3Sec2Content
        },
        {
          id: "sec-cathode-ray-tubes-specialized-beam-devices",
          title: "Cathode-Ray Tubes and Specialized Vacuum Devices: Electrostatic, Electromagnetic, Storage, and Image Tubes",
          contentAsciiDoc: chap3Sec3Content
        },
        {
          id: "sec-proofs-and-field-theorems-electron-tubes",
          title: "Formal Postulates and Theorems of Vacuum Tube Field Dynamics",
          contentAsciiDoc: chap3Sec4Content
        },
        {
          id: "sec-worked-examples-electron-tubes",
          title: "Completely Worked Technical Examples",
          contentAsciiDoc: chap3Sec5Content
        }
      ]
    }
  ]
};

const volume5JsString = `\n\nexport const SPECTRAL_ELECTRONICS_TEXTBOOK: Textbook = ${JSON.stringify(volume5Object, null, 2)};\n\nexport const TEXTBOOK_VOLUMES: Textbook[] = [\n  INITIAL_TEXTBOOK,\n  NUMBER_THEORY_TEXTBOOK,\n  GEOMETRY_ALGEBRA_TEXTBOOK,\n  PHYSICS_CHEMISTRY_TEXTBOOK,\n  SPECTRAL_ELECTRONICS_TEXTBOOK,\n];\n`;

const fullContent = beforePart + volume5JsString + `
export function generateFullAsciiDoc(textbook = INITIAL_TEXTBOOK): string {
  const chapters = getCompleteChapters(textbook.chapters);
  let adoc = \`= \${textbook.title}: \${textbook.subtitle || "Fundamentals"}\\n\`;
  adoc += \`:subtitle: \${textbook.subtitle || "Fundamentals"}\\n\`;
  adoc += \`:author: \${textbook.author}\\n\`;
  adoc += \`:doctype: book\\n\`;
  adoc += \`:toc: left\\n\`;
  adoc += \`:toc-title: Table of Contents\\n\`;
  adoc += \`:stem: latexmath\\n\`;
  adoc += \`:sectnums!:\\n\\n\`;
  adoc += \`\${textbook.description}\\n\\n\`;

  chapters.forEach((chap) => {
    adoc += \`== \${chap.title}\\n\\n\`;
    if (chap.summary) {
      adoc += \`\${chap.summary}\\n\\n\`;
    }
    chap.sections.forEach((sec) => {
      adoc += \`\${sec.contentAsciiDoc.trim()}\\n\\n\`;
    });
  });

  return adoc;
}
`;

fs.writeFileSync(filePath, fullContent, 'utf8');
console.log("Updated src/data/textbookData.ts successfully!");
