import React, { useState } from 'react';
import { ActiveView, TheoremProof, IrisDomain } from './types';
import { PRESET_THEOREMS } from './lib/irisEngine';
import { Navbar } from './components/Navbar';
import { IrisTextbook } from './components/IrisTextbook';
import { DeductionFramework } from './components/DeductionFramework';
import { IrisSandbox } from './components/IrisSandbox';
import { SpectralAnalysis } from './components/SpectralAnalysis';
import { TheoremLibrary } from './components/TheoremLibrary';
import { AIProofAssistant } from './components/AIProofAssistant';
import { AxiomWorkbench } from './components/AxiomWorkbench';
import { InfoModal } from './components/InfoModal';

export default function App() {
  const [activeTab, setActiveTab] = useState<ActiveView['tab']>('textbook');
  const [currentProof, setCurrentProof] = useState<TheoremProof>(
    PRESET_THEOREMS[0] as TheoremProof
  );
  const [infoModalOpen, setInfoModalOpen] = useState<boolean>(false);

  // Assistant prompt state for passing from library or deduction
  const [assistantPrompt, setAssistantPrompt] = useState<string>('');
  const [assistantDomain, setAssistantDomain] = useState<IrisDomain>('Number Theory');

  // Load theorem into Deduction Framework
  const handleLoadTheorem = (proof: TheoremProof) => {
    setCurrentProof(proof);
    setActiveTab('deduction');
  };

  // Open Search & Inference Engine Assistant with custom prompt
  const handleOpenAiAssistantWithPrompt = (prompt: string, domain: IrisDomain) => {
    setAssistantPrompt(prompt);
    setAssistantDomain(domain);
    setActiveTab('assistant');
  };

  // Import proof generated by Search & Inference Engine Assistant into workspace
  const handleImportGeneratedProof = (proof: TheoremProof) => {
    setCurrentProof(proof);
    setActiveTab('deduction');
  };

  // Export proof/workspace data as JSON
  const handleExportWorkspace = () => {
    const dataStr =
      'data:text/json;charset=utf-8,' +
      encodeURIComponent(JSON.stringify(currentProof, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute(
      'download',
      `iris_deduction_${currentProof.id}.json`
    );
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="min-h-screen bg-[#0c0c0c] text-slate-100 font-sans selection:bg-amber-500 selection:text-black flex flex-col">
      {/* Top Navbar */}
      <Navbar
        activeTab={activeTab}
        setActiveTab={setActiveTab}
        onOpenInfoModal={() => setInfoModalOpen(true)}
        onExportWorkspace={handleExportWorkspace}
      />

      {/* Main Content Workspace */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {activeTab === 'textbook' && <IrisTextbook />}

        {activeTab === 'deduction' && (
          <DeductionFramework
            currentProof={currentProof}
            setCurrentProof={setCurrentProof}
            onOpenAiAssistant={() => setActiveTab('assistant')}
          />
        )}

        {activeTab === 'sandbox' && <IrisSandbox />}

        {activeTab === 'spectral' && <SpectralAnalysis />}

        {activeTab === 'library' && (
          <TheoremLibrary
            onLoadTheorem={handleLoadTheorem}
            onOpenAiAssistantWithPrompt={handleOpenAiAssistantWithPrompt}
          />
        )}

        {activeTab === 'assistant' && (
          <AIProofAssistant
            onImportGeneratedProof={handleImportGeneratedProof}
            initialPrompt={assistantPrompt}
            initialDomain={assistantDomain}
          />
        )}

        {activeTab === 'axioms' && <AxiomWorkbench />}
      </main>

      {/* Info Modal */}
      <InfoModal isOpen={infoModalOpen} onClose={() => setInfoModalOpen(false)} />

      {/* Footer */}
      <footer className="bg-[#121212] py-6 text-center text-xs text-slate-500">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-2">
          <div>
            Iris Number System Inference Engine • Discrete Analysis & Number Theory
          </div>
          <div className="font-mono text-slate-500">
            basis: {'{1, ι, ϖ, ϑ}'} • τ = (1+√5)/2
          </div>
        </div>
      </footer>
    </div>
  );
}
